### PR TITLE
Replace k8s.io/apimachinery/pkg/util/clock with k8s.io/utils/clock

### PR DESCRIPTION
**Pull request by hezhizhen**
Thank you for contributing to Velero!

# Please add a summary of your change

Replace k8s.io/apimachinery/pkg/util/clock with k8s.io/utils/clock .

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by blackpiglet** [comment]
Please add a changelog file according to this document https://velero.io/docs/v1.5/code-standards/#adding-a-changelog.

**Comment by hezhizhen** [comment]
> Please add a changelog file according to this document https://velero.io/docs/v1.5/code-standards/#adding-a-changelog.

Done. PTAL

**Review by blackpiglet — APPROVED** [review]

**Comment by hezhizhen** [comment]
@qiuming-best Please take a look.

**Comment by hezhizhen** [comment]
I rebased this PR. @blackpiglet @qiuming-best

**Review by blackpiglet — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
