### PR TITLE
Add document describing manual test cases

### LINKED ISSUE #3579: Document manual testing steps
Make a checklist of tests that should be performed by hand before the release is finished.  This is just formalizing the existing steps, no need to add stuff that hasn't been covered in the past.  We should probably keep this as a doc, perhaps TESTING.md but if you think that doesn't work, we can leave it in a google doc or something.

### PR DESCRIPTION
**Pull request by zubron**
# Please add a summary of your change
This introduces a new document, `TESTING.md`, which describes manual
tests that are currently run as part of a Velero release and test cases
that we will want to introduce for future releases.

Signed-off-by: Bridget McErlean <bmcerlean@vmware.com>

# Does your change fix a particular issue?

Fixes #3579 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by ashish-amarnath — DISMISSED** [review]
Thanks for putting this together!

**Review by carlisia — CHANGES_REQUESTED** [review]
@zubron I'm terribly sorry to not have mentioned/thought of this when we discussed adding a markdown file to the repo. This really needs to be part of the website documentation, much like the release instructions for maintainers: https://velero.io/docs/v1.5/maintainers/#creating-a-release. In other words, a link to it in that page, but also a page that is integrated in the website just like the others.

This would also give more visibility for users to know what we are looking at when we test releases.

**Comment by carlisia** [comment]
The content LGTM though :)

**Comment by ashish-amarnath** [comment]
@zubron Can you please address Carlisia's comment?

**Review by dsu-igeek — APPROVED** [review]
LGTM, thanks!

**Review by carlisia — APPROVED** [review]

**Pull request merged**
