### PR TITLE
Update CloudCasa listing in ADOPTERS.md

### PR DESCRIPTION
**Pull request by bobadair**
Update CloudCasa listing in ADOPTERS.md

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by reasonerjt — APPROVED** [review]

**Review by ywk253100 — APPROVED** [review]

**Comment by ywk253100** [comment]
@bobadair Could you add your sign-off to pass the DCO checking?

**Comment by bobadair** [comment]
Hi @ywk253100. There is a sign-off on the commit. It seems to not like it for some reason.

**Comment by shubham-pampattiwar** [comment]
@bobadair See if you find anything helpgul here: https://github.com/vmware-tanzu/velero/pull/7232/checks?check_run_id=19804178361

**Comment by draghuram** [comment]
I opened another PR for this change (https://github.com/vmware-tanzu/velero/pull/7439/) so this PR can be closed.

**Comment by ywk253100** [comment]
Dup of https://github.com/vmware-tanzu/velero/pull/7439, closing this one.

**Pull request closed without merging**
