### PR TITLE
Remove ref to exclude label in v1.1.0

### PR DESCRIPTION
**Pull request by SinFulNard**
In reference to https://github.com/vmware-tanzu/velero/issues/2015 - v1.1.0 does not support the use of the exclude via label for ".additional items"

### CODE REVIEW

**Comment by skriss** [comment]
You'll also need to add DCO signoff to your commit -- `git commit --amend --signoff` followed by `git push -f` should do it.

**Comment by skriss** [comment]
@SinFulNard just checking to see if you want to make revisions here. Also, `v1.2.0` is out, where this bug is fixed.

**Comment by SinFulNard** [comment]
Sorry yes @skriss I will - busy week! I'm actually working on deploying v1.2.0 today and testing! Thanks to the team for the hard work + release.

Will find some time to update this PR.

**Comment by SinFulNard** [comment]
@skriss, hopefully my wording is sufficient in the latest commit.

**Comment by skriss** [comment]
LGTM @SinFulNard, thanks for the update

**Pull request merged**
