### PR TITLE
Remove multiple single quotes from Velero backup.status.validationErrors field

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Thank you for contributing to Velero!

# Please add a summary of your change

Remove multiple single quotes from error message 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by reasonerjt** [comment]
@shubham-pampattiwar 
Thanks but could you clarify why we wanna remove the single quote?

**Comment by shubham-pampattiwar** [comment]
@reasonerjt Validation error has extra quotes around BSL name:
```
status:
  expiration: "2024-10-27T17:54:55Z"
  formatVersion: 1.1.0
  phase: FailedValidation
  validationErrors:
  - 'an existing backup storage location wasn''t specified at backup creation time
    and the default ''sample-dpa-11'' wasn''t found. Please address this issue (see
    `velero backup-location -h` for options) and create a new backup. Error: BackupStorageLocation.velero.io
    "sample-dpa-11" not found'
  version: 1
```
With this change the extra quotes are removed:
```
status:
  expiration: "2024-10-27T18:20:38Z"
  formatVersion: 1.1.0
  phase: FailedValidation
  validationErrors:
  - 'an existing backup storage location wasn''t specified at backup creation time
    and the default sample-dpa-11 wasn''t found. Please address this issue (see `velero
    backup-location -h` for options) and create a new backup. Error: BackupStorageLocation.velero.io
    "sample-dpa-11" not found'
```

**Comment by kaovilai** [comment]
`wasn''t` still looks bad
```
location wasn''t specified
```

**Comment by shubham-pampattiwar** [comment]
> `wasn''t` still looks bad
> 
> ```
> location wasn''t specified
> ```

Updated the error message:
```
validationErrors:
  - 'an existing backup storage location was not specified at backup creation time
    and the default sample-dpa-11 was not found. Please address this issue (see `velero
    backup-location -h` for options) and create a new backup. Error: BackupStorageLocation.velero.io
    "sample-dpa-11" not found'
```

**Review by kaovilai — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
