### PR TITLE
✨ ⚠️ Remove CSI volumesnapshot artifact deletion

### LINKED ISSUE #3733: Use DeleteItemAction plugins to cleanup CSI snapshot artifacts
Velero special cases CSI snapshot artifacts by explicitly handling deletion/cleanup in the [backup_deletion_controller](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_deletion_controller.go#L374-L386)

**Describe the solution you'd like**
velero-plugin-for-csi should implement DeleteItemAction plugins to handle the cleanup of CSI voluemsnapshot artifacts instead of having core Velero handle it for them

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by ashish-amarnath**
⚠️ This change is incompatible with velero-plugin-for-csi releases <= v0.1.2

Remove special casing of CSI volumesnapshot artifacts
from backup deletion logic as this has been moved to
a DeleteItemAction plugin in the velero-plugin-for-csi repo

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #3733 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
@carlisia the auto-assign gh action is still failing. Is this expected?
https://github.com/vmware-tanzu/velero/pull/3734/checks?check_run_id=2443982445
```
Error: HttpError: Resource not accessible by integration
```

**Comment by ashish-amarnath** [comment]
Testing
[asciicast](https://asciinema.org/a/410132)

[asciicast](https://asciinema.org/a/410131)

**Comment by ashish-amarnath** [comment]
Associated PR in the velero-plugin-for-csi repo https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/86

**Comment by carlisia** [comment]
> @carlisia the auto-assign gh action is still failing. Is this expected?
> https://github.com/vmware-tanzu/velero/pull/3734/checks?check_run_id=2443982445
> 
> ```
> Error: HttpError: Resource not accessible by integration
> ```

The issue for that fix is this one: https://github.com/vmware-tanzu/velero/issues/3723

I haven't opened a PR for it yet. Please add your reviewers manually in the mean time.

**Review by dsu-igeek — APPROVED** [review]
This looks good.  Can we put a note in the changelog that this requires the CSI change (https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/86) to keep the delete functionality?

**Review by nrb — APPROVED** [review]

**Pull request merged**
