### PR TITLE
[cherry-pick][release-1.11]Fix status.progress not getting updated for backup

### PR DESCRIPTION
**Pull request by blackpiglet**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by ShellyKa13** [comment]
Hi when are you planning on releasing 1.11.1 with this fix?

**Comment by blackpiglet** [comment]
@ShellyKa13 
The current plan is to release v1.11.1 around this September's end.
Need to wait a while to collect more PRs, and also need to wait for the new patch of Golang v1.20.x to fix CVEs.
What's your opinion about this arrangement?

**Comment by ShellyKa13** [comment]
was prepared for such a long period :) I have test which relay on the status progress report. I will check if downgrading back to 1.10 will fix the issue since I wont wait until September. thanks

**Comment by blackpiglet** [comment]
@ShellyKa13 
Sorry, I made a mistake. The release time is not that long behind. v1.11.1 is planned to release at the end of next weekend.

**Comment by ShellyKa13** [comment]
@blackpiglet hi thanks for the update, so I am waiting for it, any new update on expected release date? thanks

**Comment by blackpiglet** [comment]
@ShellyKa13 
Sorry, v1.11.1 is delayed. 
https://groups.google.com/g/golang-announce/c/q5135a9d924
Due to Golang v1.20.5 issue, need to wait for Golang v1.20.6 to come out to release Velero v1.11.1.

**Pull request merged**
