### PR TITLE
use relative path in links

### PR DESCRIPTION
**Pull request by kaovilai**
Thank you for contributing to Velero!

# Please add a summary of your change
Use relative path in links. Tested on https://velero.tig.pw as part of providing temporary solution to https://github.com/vmware-tanzu/velero/issues/4579
Replaces `https://velero.io/` with `/` for all files in repo under site/
# Does your change fix a particular issue?
Fixes path when hosted from different domain names.
Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by kaovilai** [comment]
netlify/velero/deploy-preview works. Not sure why there's also netlify/fervent-minsky-ed95cc/deploy-preview
https://deploy-preview-4583--velero.netlify.app/

**Comment by kaovilai** [comment]
would make links accessible from different base url like https://velero.netlify.app/ as well.

**Comment by jenting** [comment]
This issue #4579 is fixed and closed, is this PR still needed?

**Comment by kaovilai** [comment]
> This issue #4579 is fixed and closed, is this PR still needed?

Not needed per say to get velero.io working but it would help make future PR netlify "preview" deployments point to the right place.

**Comment by jenting** [comment]
Related to #4558

**Pull request closed without merging**
