### PR TITLE
Bump up aws sdk to aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by reasonerjt**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by danfengliu** [comment]
From nightly test results, there're 2 type of failures:
1. SnapshotCreationPerVolumeRateExceeded, this error only occurred occasionally:
`time="2023-10-07T08:55:50Z" level=error msg="Error backing up item" backup=velero/backup-1-9f346451-1fcc-4733-bfcc-574b1ee3ea04 error="error taking snapshot of volume: rpc error: code = Unknown desc = operation error EC2: CreateSnapshot, https response error StatusCode: 400, RequestID: xxxxxxxx, api error SnapshotCreationPerVolumeRateExceeded: The maximum per volume CreateSnapshot request rate has been exceeded. Use an increasing or variable sleep interval between requests." logSource="pkg/backup/backup.go:448" name=kibishii-deployment-0`


2. ListObjectsV2 error on Minio : 
`time="2023-10-07T08:38:25Z" level=error msg="fail to validate backup store" backup-storage-location=velero/bsl-cdc017e5-8459-4bf9-bb27-20db3b8c108d controller=backup-storage-location error="rpc error: code = Unknown desc = operation error S3: ListObjectsV2, https response error StatusCode: 403, RequestID: xxxxxx, HostID: xxxxxxxx, api error InvalidAccessKeyId: The Access Key Id you provided does not exist in our records." error.file="/go/src/github.com/vmware-tanzu/velero/pkg/persistence/object_store.go:198" error.function="github.com/vmware-tanzu/velero/pkg/persistence.(*objectBackupStore).IsValid" logSource="pkg/controller/backup_storage_location_controller.go:151"`

**Comment by danfengliu** [comment]
Regarding Minio access failure, it's only under condition of deploy Minio using clusterIP type of service with URL  `service-name.namespace.svc:service-port `  instead of nodePort with IP address:

- s3Url=http://minio.minio.svc:9000 - FAIL
- s3Url=http://10.10.10.x:9000 - PASS

**Review by Lyndon-Li — APPROVED** [review]

**Review by danfengliu — APPROVED** [review]

**Comment by kaovilai** [comment]
FYI this pr conflicts with https://github.com/vmware-tanzu/velero/pull/6995. When this merge, I will rebase https://github.com/vmware-tanzu/velero/pull/6995 and add unit tests to prevent future regressions

**Comment by reasonerjt** [comment]
Thanks @kaovilai

**Pull request merged**
