### PR TITLE
linter(testifylint): use Len or Empty for arrays testing

### PR DESCRIPTION
**Pull request by mmorel-35**
# Please add a summary of your change

Use [testifylint](https://github.com/Antonboom/testifylint) to use Len and Empty in tests when possible
This has been done through

```
testifylint --disable-all --enable=empty,len -fix ./...
```
It is then ensured through golangci-lint configuration

# Does your change fix a particular issue?

No

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
@mmorel-35 thanks for your work improving the code quality!

A few comments:
- I would reference this issue in the PR https://github.com/vmware-tanzu/velero/issues/6023
- to test your changes, I ran `make lint` command (which is also run by CI). That was not successful because the golangci-lint version the project uses is `v1.54.2`, and `testifylint` was added to golangci-lint in version `v1.55.0`. References: 
  - https://github.com/vmware-tanzu/velero/blob/13f4efdbc996eebf4576e02f107769f58218b988/hack/build-image/Dockerfile#L96
  - https://github.com/golangci/golangci-lint/releases/tag/v1.55.0
- This PR would not enforce that new contributions use Len and Empty in tests, because of this config https://github.com/vmware-tanzu/velero/blob/13f4efdbc996eebf4576e02f107769f58218b988/golangci.yaml#L36-L37 I already tried to fix this in https://github.com/vmware-tanzu/velero/pull/7194, but unfortunately did not get any reviews or comments from maintainers there

**Comment by mateusoliveira43** [comment]
@mmorel-35 I agree, the more simple the PR, the better!

Just want to warn maintainers that current project's config is not very reliable

**Comment by blackpiglet** [comment]
> @mmorel-35 I agree, the more simple the PR, the better!
> 
> Just want to warn maintainers that current project's config is not very reliable

I agree with your opinion. To enable linter for all test files, would be good, although it doesn't have a high priority.

**Review by blackpiglet — APPROVED** [review]

**Comment by blackpiglet** [comment]
@mmorel-35 
Sure. Thanks for your contribution.

**Comment by blackpiglet** [comment]
@mateusoliveira43 
PR needs two maintainers' approval. Involved more maintainers to take a look.

**Review by sseago — APPROVED** [review]

**Pull request merged**
