### PR TITLE
When spec.RestoreStatus is empty, don't restore status (1.9 cherry-pick)

### PR DESCRIPTION
**Pull request by sseago**
Signed-off-by: Scott Seago <sseago@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change
Fix from #5008 cherry-picked to release 1.9

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by sseago** [comment]
Note that I moved the changelogs/unreleased commit message from the main commit to the CHANGELOG-1.9.md file, since it wouldn't be listed there otherwise for the release. Let me know if that was the wrong way to approach cherry-picks that had changelog messages on main.

**Comment by sseago** [comment]
Reopening again -- I see that the other one was closed. Looks like I need to fix the changelog thing, though. I checked the docs and I should add a changelog unrelease message matching PR rather than updating 1.9 changelog.

**Review by qiuming-best — APPROVED** [review]
Lgtm

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
