### PR TITLE
Fix codespell errors

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Thank you for contributing to Velero!

# Please add a summary of your change
This PR fixes the codespell errors

# Does your change fix a particular issue?

Fix codespell errors check that is failing on most of the recent PRs

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
Thanks for the fix @shubham-pampattiwar 

I believe there is one more fix missing (bakcup ==> backup), but the other ones are false positive (**allLocations**, I believe codespell does not parse camelCase https://github.com/codespell-project/codespell/issues/196). To ignore it, just add it to https://github.com/vmware-tanzu/velero/blob/main/.github/workflows/pr-codespell.yml#L18

**Comment by sseago** [comment]
@mateusoliveira43 That's right -- the "allLocations" one is a false positive. codespell thinks we want "allocations" which is completely different than "all locations", so that change would be wrong. Maybe add "allLocations" to the ignore_words_list in pr-codespell.yaml?

**Comment by shubham-pampattiwar** [comment]
@mateusoliveira43 @sseago PTAL, Thanks !

**Comment by sseago** [comment]
OK, so now the PR adds `allLocations` to the ignore list, but I don't think that takes effect until the PR is merged, so `allLocations` usage is still flagged in the codespell failure, but on merge, the hope is that it will no longer be flagged on future PRs. I think this is good to go now.

**Comment by yanggangtony** [comment]
I enconter the same codespell problem in [pr 6924](https://github.com/vmware-tanzu/velero/pull/6924).
😂😂

**Comment by anshulahuja98** [comment]
@shubham-pampattiwar I think you can close this one.

**Pull request closed without merging**
