### PR TITLE
Fixing multipleNamespaceTest bug - Missing expect statement in test

### PR DESCRIPTION
**Pull request by jaidevmane**
Signed-off-by: Jai Subash Devmane <jdevmane@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change
- Bug Fix for multiple namespace test where Expect statement was not present
# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by sseago** [comment]
https://github.com/vmware-tanzu/velero/pull/3987 seems to be a duplicate of this fix -- the only difference is the failure message. Both PRs are failing CI tests on kind with this change in the same way, although talking to @jaidevmane just now, the tests are succeeding locally.

**Comment by ywk253100** [comment]
@jaidevmane The case random failure is a known issue https://github.com/vmware-tanzu/velero/issues/3970 and I'll raise PR to fix it.
As https://github.com/vmware-tanzu/velero/pull/3989 get merged, could you try to rebase your PR? and this should workaround the CI failure

**Comment by jaidevmane** [comment]
@ywk253100 Thank you for your guidance. I have incorporated your suggestions as mentioned.

**Comment by jaidevmane** [comment]
All checks passed. Ready to review.

**Review by ywk253100 — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Pull request merged**
