### PR TITLE
Added Eleanor to Team Bios and to Maintainers page, removed Tim

### PR DESCRIPTION
**Pull request by eleanor-millman**
Signed-off-by: Eleanor Millman <emillman@vmware.com>

Thank you for contributing to Velero!

# Added Eleanor to Team Bios and to Maintainers page, removed Tim

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by dsu-igeek — CHANGES_REQUESTED** [review]
the eleanor-millman.jpg is zero length

**Comment by dsu-igeek** [comment]
We will merge after 1.6 release

**Review by dsu-igeek — APPROVED** [review]

**Review by carlisia — APPROVED** [review]
Thank you for doing this! 👍

**Pull request merged**
