### PR TITLE
Don't move velero v1 plugins to new proto dir

### LINKED ISSUE #5262: BackupItemAction refactoring for plugin versioning isn't backwards compatible
**Describe the problem/challenge you have**
BackupItemAction refactoring for plugin versioning isn't backwards compatible. We need previous plugin release to work with velero 1.10. Instead of putting all plugins into their own package at "generated/<plugin-type>/<version", we should use that for v2, v3, etc. but assume that v1 is found in "generated" as it is now. The version negotiation code and/or wrappers should handle this rather than pushing it onto plugin authors to release a new version.

**Describe the solution you'd like**
v1 plugins live in their current dir, v2 and later in the version-specific location.

**Anything else you would like to add:**
(pr forthcoming to move the BIA plugin files back to their original location.

**Environment:**

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by sseago**
Signed-off-by: Scott Seago <sseago@redhat.com>

Thank you for contributing to Velero!

To preserve backwards compatibility, don't move velero
v1 plugins to new proto dir.

# Does your change fix a particular issue?

Fixes #5262 

# Please indicate you've done the following:

- [x ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by reasonerjt** [comment]
I think this change is a good improvement, could you please also update the section in the design https://github.com/vmware-tanzu/velero/blob/main/design/plugin-versioning.md#proto-service-definitions, to clarify that for backward compatibility the v1 files will be remained in  `pkg/plugin/proto/<plugin_kind>/`

**Comment by sseago** [comment]
@reasonerjt doc updated with the change.

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by weshayutin** [comment]
Looks good, thanks for putting this up

**Comment by shubham-pampattiwar** [comment]
Important fix, lets get this in.

**Review by blackpiglet — APPROVED** [review]

**Pull request merged**
