### PR TITLE
Use errors.Is to check for a specific error

### PR DESCRIPTION
**Pull request by Fish-pro**
Thank you for contributing to Velero!

# Please add a summary of your change

Comparing with ==  will fail on wrapped errors. Use errors.Is to check for a specific error

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by blackpiglet — APPROVED** [review]

**Comment by reasonerjt** [comment]
Currently, there are  many files importing `github.com/pkg/errors` in the codebase.
Introducing more references to the standard library `errors` will cause confusion when developers are reading the code.

I will open an issue to unify the error handling, we may choose to abandon the usage of `github.com/pkg/errors`.  
I wish to tentatively block this PR from merging to `main` branch until we have a clear plan for error handling in velero.

**Review by reasonerjt — CHANGES_REQUESTED** [review]
I wish to tentatively block this PR from merging to main branch until we have a clear plan for error handling in velero.

**Comment by blackpiglet** [comment]
@Fish-pro 
After disussion, we think it's better to put this on hold, because Velero is still using "github.com/pkg/errors" package with integrated Golang error package, we are still working on removing the "github.com/pkg/errors" from code.
After that is done, we can continue on this PR.

**Comment by reasonerjt** [comment]
Opened issue:
https://github.com/vmware-tanzu/velero/issues/5731

**Comment by Fish-pro** [comment]
> @Fish-pro After disussion, we think it's better to put this on hold, because Velero is still using "github.com/pkg/errors" package with integrated Golang error package, we are still working on removing the "github.com/pkg/errors" from code. After that is done, we can continue on this PR.

@reasonerjt Thanks for your reply, I got it

**Pull request closed without merging**
