### PR TITLE
Add support for block volumes

### LINKED ISSUE #6548: Support backup on volumeMode block via Data mover (Kopia)
**Describe the problem/challenge you have**

Currently Velero Datamover does not support backup for PVs whose volumeMode is `Block`.

**Describe the solution you'd like**

Make Velero Datamover Backup and restore operations work for PVs with `volumeMode` as `Block`

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by dzaninovic**
Thank you for contributing to Velero!

# Please add a summary of your change
Cherry-pick https://github.com/vmware-tanzu/velero/pull/6680 to 1.12 release.

# Does your change fix a particular issue?

Fixes #6548

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [X] Updated the corresponding documentation in `site/content/docs/main`.

# Testing

I ran automated tests and retested backup and restore of block and filesystem PVC with md5 verification.

### CODE REVIEW

**Review by shubham-pampattiwar — APPROVED** [review]

**Review by sseago — DISMISSED** [review]

**Comment by sseago** [comment]
@dzaninovic Oh, I guess you need to update the changelog filename to reflect the cherry-pick PR number.

**Comment by dzaninovic** [comment]
> @dzaninovic Oh, I guess you need to update the changelog filename to reflect the cherry-pick PR number.

@sseago, I was not sure if that needs to be updated since it is a cherry-pick.
I updated it now.

**Review by shubham-pampattiwar — APPROVED** [review]

**Comment by sseago** [comment]
@dzaninovic one more thing -- looks like this PR needs to be rebased after recent merges to release-1.12

**Comment by dzaninovic** [comment]
> @dzaninovic one more thing -- looks like this PR needs to be rebased after recent merges to release-1.12

@sseago, I rebased it again.

**Comment by kaovilai** [comment]
need dco

**Comment by kaovilai** [comment]
im assuming it wants signoff as last line in commit message.

**Comment by kaovilai** [comment]
Just `git commit --signoff --amend --no-edit`

**Comment by dzaninovic** [comment]
I fixed the DCO issue by moving it to the last line.

**Review by sseago — APPROVED** [review]

**Pull request merged**
