### PR TITLE
Bump Go to 1.18

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Thank you for contributing to Velero!

# Please add a summary of your change

/kind changelog-not-required

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by sseago — DISMISSED** [review]

**Comment by qiuming-best** [comment]
@Lyndon-Li please find the crash issue related with upgrade golang v1.18

**Comment by Lyndon-Li** [comment]
FYI, we have a [crash issue](https://github.com/vmware-tanzu/velero/issues/4942) when upgrading to go 1.18.
As the initial check, the problem may not happen with Velero 1.19 which uses github.com/json-iterator/go v1.1.12, see [here](https://github.com/vmware-tanzu/velero/blob/release-1.9/go.mod#:~:text=github.com/json%2Diterator/go%20v1.1.12%20//%20indirect).

Please double confirm this by testing and we need to do a well-rounded test after this upgrade.

**Comment by gliptak** [comment]
@Lyndon-Li @qiuming-best HEAD is already in the corrected versions of the libraries

https://github.com/golang/go/issues/48238

would https://github.com/vmware-tanzu/velero/pull/5285 help?

**Comment by gliptak** [comment]
after rebase, build  failed with

```
--- FAIL: TestGetVolumesRepositoryType (0.00s)
    --- FAIL: TestGetVolumesRepositoryType/mismatch_repository_type (0.00s)
        restorer_test.go:87: 
            	Error Trace:	restorer_test.go:87
            	Error:      	Error message not equal:
            	            	expected: "multiple repository type in one backup, current type fake-type1, differential one [type fake-type2, snapshot ID fake-snapshot-id-2, uploader fake-uploader-2]"
            	            	actual  : "multiple repository type in one backup, current type fake-type2, differential one [type fake-type1, snapshot ID , uploader ]"
            	Test:       	TestGetVolumesRepositoryType/mismatch_repository_type
FAIL
coverage: 36.3% of statements
FAIL	github.com/vmware-tanzu/velero/pkg/podvolume	0.034s
```

**Review by blackpiglet — APPROVED** [review]

**Review by Lyndon-Li — APPROVED** [review]

**Pull request merged**
