### PR TITLE
Updating restic document for OpenShift cluster having version 4.1 or later

### PR DESCRIPTION
**Pull request by shashank855**
Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>

### CODE REVIEW

**Comment by skriss** [comment]
@shashank855 thanks for this PR, LGTM!

**Comment by skriss** [comment]
could you make the same change in `site/docs/v1.2.0/restic.md`, so it's reflected in the versioned docs for the latest release as well?

**Comment by nrb** [comment]
:+1: Will approve once the change is also applied to the `v1.2.0` version.

**Comment by skriss** [comment]
great thanks @shashank855! @nrb I'll let you merge when ready.

**Pull request merged**
