### PR TITLE
Add DataUpload Result and CSI VolumeSnapshot check for restore PV.

### PR DESCRIPTION
**Pull request by blackpiglet**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by anshulahuja98** [comment]
@blackpiglet is this PR for resolving the issue discussed in https://github.com/vmware-tanzu/velero/issues/6595
If yes, do you want to take it as different PR/commit which can be cherry picked to previous releases?

**Comment by blackpiglet** [comment]
> @blackpiglet is this PR for resolving the issue discussed in #6595 If yes, do you want to take it as different PR/commit which can be cherry picked to previous releases?

@anshulahuja98 
Yes, this PR is used to add the backward-compatible fix for the previous releases.
Sure, after this PR is merged, I will create cherry-pick PRs for older releases.

**Comment by Lyndon-Li** [comment]
@blackpiglet Shouldn't the implementation use the backup volume info in design #6962?

**Comment by blackpiglet** [comment]
> @blackpiglet Shouldn't the implementation use the backup volume info in design #6962?

The reason this change is also needed for the main release is that the main Velero release also needs to handle the backup generated by the old Velero.
The old version backup doesn't have the VolumeInfo metadata.
The main Velero needs to have this PR as a fall-back.

**Review by Lyndon-Li — APPROVED** [review]

**Comment by blackpiglet** [comment]
> @blackpiglet So for the implementation PR of the design #6962, you will be updating the switch case function [here](https://github.com/vmware-tanzu/velero/pull/7061/files#diff-e0498755be37b683528e2569667d67818bb676827c420aab49adc62cb6d47fe3R1293) to check for `VolumeInfo` and use that struct/file/data if present or else fall back on the current PR's code, Is this the plan ? Also, the CP would be clean and easy to backup-port to earlier releases. ++ @blackpiglet

@shubham-pampattiwar 
Exactly. The cherry-pick will only contain this PR's content.

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
