### PR TITLE
📖  Add docs to troubleshoot cloud-credentials

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

### CODE REVIEW

**Review by zubron — CHANGES_REQUESTED** [review]
Thanks for adding this! Should these troubleshooting steps also prompt users to check the restic DaemonSet as well? I don't think they would need to have the same level of detail, just point out that if restic is enabled, they should also check the volume mounts for those pods.

**Comment by ashish-amarnath** [comment]
@zubron Adding restic info is a good call! Fixed it. PTAL

**Review by zubron — APPROVED** [review]
Looks good - thanks for making the changes!

**Review by carlisia — APPROVED** [review]
👍  thank you!

**Pull request merged**
