### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by xrstf**
Our CI system noticed a few typos in the CRDs.

### CODE REVIEW

**Comment by xrstf** [comment]
I don't think this change warrants a changelog entry.

**Review by nrb — APPROVED** [review]
Thanks for catching these @xrstf!

**Comment by carlisia** [comment]
Wait. I expected at this point this PR would have conflicting files, since all the fixes in it have been fixed here: https://github.com/vmware-tanzu/velero/pull/3057. Weird.

**Comment by zubron** [comment]
@carlisia I was expecting the same. I checked this PR out locally and rebased onto main and saw that the only outstanding difference was a new line being added to the end of a file. Perhaps GitHub only shows the diff against the base branch at the point when the PR was created? I'm not sure how to force the diff to be against the latest commit on main.

**Comment by carlisia** [comment]
@xrstf thank you for this change. There was another PR (merged) that addressed typos in the files in this PR as well as others so I will close this one out.

**Pull request closed without merging**
