### PR TITLE
Revert PR #6907 as site is not deploying

### PR DESCRIPTION
**Pull request by OrlinVasilev**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by kaovilai** [comment]
https://deploy-preview-6980--velero.netlify.app/docs/v1.12/ did deploy

**Comment by OrlinVasilev** [comment]
https://deploy-preview-6981--velero.netlify.app/

**Comment by kaovilai** [comment]
can you publish your netlify settings?
image

**Comment by OrlinVasilev** [comment]
image

**Comment by kaovilai** [comment]
also env
image

**Comment by kaovilai** [comment]
Can you unset everything [like so](https://github.com/vmware-tanzu/velero/pull/6981#issuecomment-1771119536)?

That way the toml is the source of truth.

Otherwise commit the build settings to site building doc

**Comment by OrlinVasilev** [comment]
The new netlify white theme is so bad :)

**Comment by kaovilai** [comment]
I think having it be all in toml would be best for other collaborators to contribute.. if unsetting the config in netlify settings fixes it.

**Comment by kaovilai** [comment]
So basically what you have in https://github.com/vmware-tanzu/velero/pull/6981#issuecomment-1771124309
is not settable today. Netlify UI today is broken as I noted in https://answers.netlify.com/t/deploy-did-not-succeed-deploy-directory-site-site-public-does-not-exist/103160/3?u=kaovilai

Hence I had to exclusively use the toml to set the right path.

**Comment by kaovilai** [comment]
What I have works today.
image

You will note that the package directory [is not](https://github.com/vmware-tanzu/velero/pull/6981#issuecomment-1771146546) being overwritten.

**Comment by kaovilai** [comment]
In any case.. the bug (netlify UI) I reported was fixed... so we can go ahead with this PR and I will have to set package directory in the netlify UI.

Should add the settings here to the doc tho..

Without the knowledge of velero build settings here it basically doesn't build.

**Comment by kaovilai** [comment]
You can trigger by going to https://app.netlify.com/sites/velero/deploys
image

**Comment by OrlinVasilev** [comment]
here you go ! https://6531550e78c95b3eaacf6de1--velero.netlify.app/docs/main/file-system-backup/
image

**Comment by kaovilai** [comment]
woot!

**Comment by kaovilai** [comment]
https://app.netlify.com/sites/velero/deploys/6531550e78c95b3eaacf6de1 looks like a deploy for this PR
I didn't mean deploy for this PR.. I mean deploy of current main without this PR

**Comment by OrlinVasilev** [comment]
nope! :(
image
let's merge that :)

**Comment by kaovilai** [comment]
without setting publish directory to public

**Comment by OrlinVasilev** [comment]
with my fix it's ok

**Comment by kaovilai** [comment]
diffing logs

**Comment by kaovilai** [comment]
```
❯ Flags
  baseRelDir: true
```
[mine has baseRelDir true](https://app.netlify.com/sites/velero-k/deploys/653164e2a3e6b20008fdee60#L44)

Velero has `baseRelDir: false`
https://app.netlify.com/sites/velero/deploys/65316342d07d724c54eef0ec#L58

**Comment by kaovilai** [comment]
So your PR is not compatible with my netlify flags and vice versa :(

**Comment by kaovilai** [comment]
I need to ask somebody how to change this flag but based on [docs](https://docs.netlify.com/configure-builds/overview/) it should be true for everyone else :(
> The directory is relative to the base directory

**Comment by kaovilai** [comment]
> All paths configured in the netlify.toml should be absolute paths relative to the [base directory](https://docs.netlify.com/configure-builds/overview/#definitions), which is the root by default (/).

[#](https://docs.netlify.com/configure-builds/file-based-configuration/#build-settings)

**Comment by kaovilai** [comment]
heh.
> ## baseRelDir
> 
> Boolean flag intended for backward compatibility. This is set for any sites created since the end of 2019.
> 
> When unset:
> 
> - The second pass when searching `netlify.toml` described above does not apply
> - Paths in `netlify.toml` are relative to the repository root instead of the build directory

https://github.com/netlify/build/blob/72e33da1f3108c114b88ebd91602df2d325485a2/packages/config/docs/file_paths.md?plain=1#L60-L67

**Review by blackpiglet — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
@sseago can you review please

**Review by sseago — APPROVED** [review]

**Comment by OrlinVasilev** [comment]
THANK YOU

**Pull request merged**
