### PR TITLE
fix links to azure setup instructions

### LINKED ISSUE #1960: Velero debugging documentation missing: https://velero.io/docs/master/debugging-install/0
**What steps did you take and what happened:**

Tried to access velero debugging instructions for azure: 

https://velero.io/docs/master/debugging-install/0

**What did you expect to happen:**

The documentation should ideally be there.

**The output of the following commands will help us better understand what's going on**:

https://velero.io/docs/master/debugging-install/0

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

n/a

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

Closes #1960

### CODE REVIEW

**Comment by skriss** [comment]
@carlisia or @prydonius this should be ready to merge, thanks!

**Comment by skriss** [comment]
one review's sufficient here, merging.

**Comment by carlisia** [comment]
@skriss should we move the debugging sections into their respective plugins?

I noticed the link (https://velero.io/docs/master/debugging-install/) for the azure setup instructions (updated in this PR) is broken now that the `azure-config` file has been deleted. Was gonna fix it but wanted to check on ^ first.

**Comment by skriss** [comment]
yeah, I think that probably makes sense

**Pull request merged**
