### PR TITLE
Draft of TOC updates

### LINKED ISSUE #4531: Update docs table of contents
As a Velero user, I want to be able to easily find answers to my questions in the docs.

However, currently, when I look for information on restore, for example, I see information on restore spread over several categories. So, it would be great to consolidate some information (like for backup and for restore) as well as perhaps rename some of the category names. Ideas below.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by a-mccarthy**
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

This is a draft of proposed TOC updates for the docs site. 

Notes:
* This PR doesn't currently take into account any redirects
* The TOC is getting a little long, so we might want to think about add an expandable/collapsible feature.

# Does your change fix a particular issue?

Fixes #4531 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by a-mccarthy** [comment]
@eleanor-millman here is a draft of the TOC changes based on what we were talking about in the issue. 

you can view the changes in the preview: https://deploy-preview-4812--velero.netlify.app/docs/main/

**Comment by a-mccarthy** [comment]
made this a draft because there is still work to be done. All feedback is welcome!!

**Comment by eleanor-millman** [comment]
@a-mccarthy Thanks so much for making these changes! A few thoughts:

1) I wonder if we should move "Backup storage locations and volume snapshot locations" from under the Intro to under Backup? Or to under Install (if you configure them during install)? not sure if I am right, just wanted to hear your thoughts...

2) In the TOC, it says volume "snapstot"' locations. 
 
3) I think "Use Cases" was a good transitional header. A future TOC project would probably be to delve into that section and tweak/reorganize things, but for this round, this is great.

4) Would it make sense to put API types above Troubleshoot? For me, it feels like a more natural order, but feel free to disagree!

5) Where did the IBM, Tencent, and Oracle pages come from? I only see one file changed in the PR and it adds them, instead of moving them from elsewhere.

Thanks!

**Comment by a-mccarthy** [comment]
>I wonder if we should move "Backup storage locations and volume snapshot locations" from under the Intro to under Backup? Or to under Install (if you configure them during install)? not sure if I am right, just wanted to hear your thoughts...

I'm not sure that the "Backup storage locations and volume snapshot locations" page really fits in the install section. It's written more like an introductory page that gives and an overview of Velero concepts. I think thats why the page was title "About locations" in the TOC and is in the Intro section. I'm not sure that it fits 100% great where it is, but i'm also not sure it fits any better in the other sections either. 

> 2. In the TOC, it says volume "snapstot"' locations.

updated.

> 3. I think "Use Cases" was a good transitional header. A future TOC project would probably be to delve into that section and tweak/reorganize things, but for this round, this is great.

ok

> 4. Would it make sense to put API types above Troubleshoot? For me, it feels like a more natural order, but feel free to disagree!

Yea, we can move the API section up. i updated this. 

> 5. Where did the IBM, Tencent, and Oracle pages come from? I only see one file changed in the PR and it adds them, instead of moving them from elsewhere.

The IBM, Tencent, and Oracle pages are currently available on the site, but dont have a link in the TOC. So for example, https://velero.io/docs/main/contributions/ibm-config/ is a page on the site, but you can only get to it by having the link or searching. There is some content in the [/contributions folder](https://github.com/vmware-tanzu/velero/tree/main/site/content/docs/main/contributions) that isn't link in the TOC.

**Comment by a-mccarthy** [comment]
@OrlinVasilev can you take a look at this? i'd be interested in what you think of the changes. thanks!

https://deploy-preview-4812--velero.netlify.app/

**Pull request closed without merging**
