### PR TITLE
Add defaultVolumesToRestic to schedule api docs

### LINKED ISSUE #4352: Add defaultVolumesToRestic option to Schedule API Documentation
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
Currently, we can't set defaultVolumesToRestic in schedule api/ yaml template. In my case, I need to setup two schedules, one is to backup some namespaces with restic, and to backup other namespaces without restic.

I know I can use opt-in approach, but it's not ideal to add annotations to every pod in a namespace.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add a defaultVolumesToRestic option to schedule api, when set to true, the velero will apply backup with restic.
Default value will be the global setting.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by a-mccarthy**
Signed-off-by: Abigail McCarthy <mabigail@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change
Updates docs to include the defaultVolumesToRestic as an available setting in the Schedule api spec

# Does your change fix a particular issue?

Fixes #4352 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by a-mccarthy** [comment]
Do we think it worth creating a separate issue to review all out API docs to make sure that they are up to date? Is there any way we can easily check that?

**Comment by zubron** [comment]
> Do we think it worth creating a separate issue to review all out API docs to make sure that they are up to date? Is there any way we can easily check that?

@a-mccarthy Yes, that's definitely worth doing. I think the only way to do it is to check the CRD definitions for each type (e.g. [Backup CRD](https://github.com/vmware-tanzu/velero/blob/main/config/crd/v1/bases/velero.io_backups.yaml)) or check the Go definitions (e.g. [backup definition](https://github.com/vmware-tanzu/velero/blob/main/pkg/apis/velero/v1/backup.go)). The CRD definitions are closer to what would go in the API docs but they aren't as readable.

**Review by zubron — APPROVED** [review]

**Comment by a-mccarthy** [comment]
I created an issue to review and update the api docs, https://github.com/vmware-tanzu/velero/issues/4448

**Review by ywk253100 — APPROVED** [review]

**Pull request merged**
