### PR TITLE
Add documentation search to the site

### LINKED ISSUE #2124: Add search to the website
The website, especially the docs, can really use a search function.

### PR DESCRIPTION
**Pull request by jonasrosland**
This will add documentation search to the site, and fixes #2124 

Signed-off-by: jonasrosland <jrosland@vmware.com>

### CODE REVIEW

**Comment by michmike** [comment]
when you search the left pane that says "documemtation" moves the "n" to its own line. we need to fix that

**Comment by carlisia** [comment]
Checked it on my phone and looks same as good!

**Comment by jonasrosland** [comment]
I've updated the PR with a new style, that works even better on mobile as well. Let me know what you think.

**Comment by michmike** [comment]
lgtm. great job @jonasrosland

**Pull request merged**
