### PR TITLE
Fix: add init log option for velero controller-runtime manager.

### LINKED ISSUE #3737: velero backup logs <backup_name> hangs forever  - More debug log needed in velero server.
**What steps did you take and what happened:**
Trying to get the logs of a backup fail and the command hangs forever. 

**What did you expect to happen:**
To see the logs generated for that particular backup

**The output of the following commands will help us better understand what's going on**:

- `kubectl logs deployment/velero -n velero`
```
time="2021-04-27T08:20:38Z" level=error msg="Error updating download request" controller=download-request downloadRequest=velero/velero-1619435026-dailybackups-20210426110358-20210426151139 error="downloadrequests.velero.io \"velero-1619435026-dailybackups-20210426110358-20210426151139\" not found" logSource="pkg/controller/download_request_controller.go:81"
time="2021-04-27T08:20:58Z" level=error msg="Error updating download request" controller=download-request downloadRequest=velero/velero-1619435026-dailybackups-20210426110358-20210426142201 error="downloadrequests.velero.io \"velero-1619435026-dailybackups-20210426110358-20210426142201\" not found" logSource="pkg/controller/download_request_controller.go:81"
time="2021-04-27T08:21:09Z" level=error msg="Error updating download request" controller=download-request downloadRequest=velero/velero-1619435026-dailybackups-20210426110358-20210426151211 error="downloadrequests.velero.io \"velero-1619435026-dailybackups-20210426110358-20210426151211\" not found" logSource="pkg/controller/download_request_controller.go:81"
time="2021-04-27T08:21:26Z" level=info msg="Validating backup storage location" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
time="2021-04-27T08:21:26Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
time="2021-04-27T08:21:41Z" level=error msg="Error updating download request" controller=download-request downloadRequest=velero/velero-1619435026-dailybackups-20210426110358-20210426125922 error="downloadrequests.velero.io \"velero-1619435026-dailybackups-20210426110358-20210426125922\" not found" logSource="pkg/controller/download_request_controller.go:81"
time="2021-04-27T08:21:52Z" level=info msg="Processing new ServerStatusRequest" controller=server-status-request logSource="pkg/controller/server_status_request_controller.go:90" phase= serverStatusRequest=velero/velero-cli-mlqp9
time="2021-04-27T08:22:27Z" level=info msg="Validating backup storage location" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:114"
time="2021-04-27T08:22:27Z" level=info msg="Backup storage location valid, marking as available" backup-storage-location=default controller=backup-storage-location logSource="pkg/controller/backup_storage_location_controller.go:121"
```
- `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         velero-1619435026-dailybackups-20210426110358
Namespace:    velero
Labels:       app.kubernetes.io/instance=velero-1619435026
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=velero
              helm.sh/chart=velero-2.17.2
              velero.io/schedule-name=velero-1619435026-dailybackups
              velero.io/storage-location=default
Annotations:  helm.sh/hook=post-install,post-upgrade
              helm.sh/hook-delete-policy=before-hook-creation
              velero.io/source-cluster-k8s-gitversion=v1.18.2
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=18

Phase:  Completed

Errors:    0
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  backupData=daily

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2021-04-26 12:04:03 +0100 BST
Completed:  2021-04-26 12:04:19 +0100 BST

Expiration:  2021-05-26 12:04:01 +0100 BST

Total items to be backed up:  7
Items backed up:              7
```

Velero-Native Snapshots:  1 of 1 snapshots completed successfully (specify --details for more information)
- `velero backup logs <backupname>`
- Hangs

Velero version
Client:
	Version: v1.6.0
	Git commit: -
Server:
	Version: v1.6.0

**Anything else you would like to add:**
The issue seems to be the command DownloadRequest never receives a URL so keeps looping waiting for that field to not be empty. velero has been deployed to a private AKS cluster

**Environment:**

- Velero features (use `velero client config get features`): 
`features: <NOT SET>`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:18:00Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
`Azure Private AKS`
- Cloud provider or hardware configuration:
`Azure`
- OS (e.g. from `/etc/os-release`):
`Tried on both Mac and Ubuntu 20.04`

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by blackpiglet**
Signed-off-by: Xun Jiang jxun@vmware.com

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #3737

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by jenting — COMMENTED** [review]
In general, LGTM
But it's better to have a changelog if it's fixing an issue.

**Comment by blackpiglet** [comment]
@jenting 
Thanks. I will update the changelog.

**Review by jenting — APPROVED** [review]

**Comment by ywk253100** [comment]
@blackpiglet Could we try to address the issues mentioned [here](https://github.com/vmware-tanzu/velero/issues/3737#issuecomment-961856825)? If we simply set a `zap` logger for the controller, there will be two kinds of log formats. And we also need to support setting the log level for the new logger. Implement the logger interface with `logrus` is one solution

**Comment by blackpiglet** [comment]
@ywk253100 

I checked whether it's possible to use logrus logger, but it seems the manager only takes logger implements the github.com/go-logr/logr interface. logrus and logr's interface are not compatible.

[	Logger logr.Logger](https://github.com/kubernetes-sigs/controller-runtime/blob/4d10a0615b11507451ecb58bfd59f0f6ef313a29/pkg/manager/manager.go#L138)

**Comment by sseago** [comment]
@blackpiglet check out 	"github.com/bombsimon/logrusr" -- it allows you to implement the go-logr logr.Logger interface with a logrus logger.

**Comment by sseago** [comment]
@blackpiglet For the openshift velero plugin used with OADP, we needed to call a shared func that was used both in the plugin (which uses velero's logrus implementation) and in the crane migration tool (which uses go-logr Loggers). 

This line calls `logrusr.NewLogger(p.Log)`, passing in a `logrus.FieldLogger`, and getting a `logr.Logger`
https://github.com/openshift/openshift-velero-plugin/blob/master/velero-plugins/imagestream/backup.go#L88

The func we're calling there takes a `logr.Logger` param rather than a `logrus.FieldLogger`

**Comment by blackpiglet** [comment]
@sseago 
Thanks a lot. Your suggestion really saves a lot of my work!
As a matter of fact, I tried to write a log adaptor by myself yesterday. Although it worked, there are still a lot of things I'm clear about in the code.

**Review by sseago — APPROVED** [review]

**Comment by ywk253100** [comment]
@blackpiglet And one thing we need to do is to remove the similar code like [this](https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/download_request_controller.go#L67) which will output duplicated logs after we set logger for the controller.

We can do this during the controller refactoring from kubebuilder v2 to v3, but please open a new issue for this if you don't include the change in this PR

**Comment by blackpiglet** [comment]
@ywk253100 
Great catch. After adding the new logger, it may introduce duplicated log entries. 
I opened a new issue to trace the potential duplicated logs. https://github.com/vmware-tanzu/velero/issues/4368

**Review by ywk253100 — APPROVED** [review]

**Pull request merged**
