### PR TITLE
Cherry-pick #6917 to release 1.12

### PR DESCRIPTION
**Pull request by 27149chen**
support JSON Merge Patch and Strategic Merge Patch in Resource Modifiers

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by anshulahuja98** [comment]
@27149chen I am not sure if we should take a big change now to 1.12
I don't think this was in initial plan to pull to 1.12

**Comment by anshulahuja98** [comment]
@27149chen I'll recommend this go out in 1.13
We can close this PR for now.

**Comment by ywk253100** [comment]
@27149chen You need to rebase the commit to resolve `This branch is out-of-date with the base branch` warning

**Review by ywk253100 — APPROVED** [review]

**Review by Lyndon-Li — APPROVED** [review]

**Comment by anshulahuja98** [comment]
1 small nitpick - we missed making the PR title reflect the cherry picked feature.

**Comment by 27149chen** [comment]
@anshulahuja98 what's the correct title for cherry-pick prs?

**Comment by anshulahuja98** [comment]
PR title guidelines: https://github.com/sseago/velero/blob/cd7e2d6fcc515c11098d85ef933b2089fb6e0770/site/content/docs/main/code-standards.md?plain=1#L11

**Comment by anshulahuja98** [comment]
Should have ideally included the original PR naming
something to indicate what this PR is for apart from the Issue number

**Pull request merged**
