### PR TITLE
Change maintainer

### PR DESCRIPTION
**Pull request by carlisia**
Signed-off-by: Carlisia <carlisia@vmware.com>

### CODE REVIEW

**Comment by carlisia** [comment]
I've re-run the check twice after adding the `changelog-not-required` label 🤷‍♀️

**Comment by nrb** [comment]
@carlisia The changelog check isn't merge blocking, it's mostly a reminder for us.

**Comment by ashish-amarnath** [comment]
Closing and re-opening has been a reliable way to re-trigger the changelog CI check. This is for some reason different that just retrying the actions.

**Comment by ashish-amarnath** [comment]
@nrb this PR should be ready for merge.

**Pull request merged**
