### PR TITLE
enable e2e tests to choose crd apiVersion

### PR DESCRIPTION
**Pull request by sseago**
Signed-off-by: Scott Seago <sseago@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change
Enables running e2e tests with either v1 or v1beta1 CRDs

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by sseago** [comment]
Note that this PR depends on https://github.com/vmware-tanzu/velero/pull/3614/files to be merged first.

**Comment by sseago** [comment]
The "Run the E2E test" checks are expected to fail right now, since some of the required code is not yet merged.

**Comment by jenting** [comment]
#3614 PR merged, please help rebase it :)

**Review by dsu-igeek — APPROVED** [review]
LGTM - thanks!

**Comment by zubron** [comment]
@sseago Could you please run `make update` and push the changes? Thanks! I tried to do it myself but I don't have permission to push to this branch.

**Comment by sseago** [comment]
@zubron On it. Will push an update shortly.

**Review by zubron — APPROVED** [review]
Thanks!

**Review by ywk253100 — APPROVED** [review]

**Pull request merged**
