### PR TITLE
added documentation for how velero handles encryption

### LINKED ISSUE #3065: Improve docs on encryption
**Describe the problem/challenge you have**
How does Velero handle encryption? Does it encrypt anything by default?

**Describe the solution you'd like**
We should add docs describing encryption.

Velero's backups are split into 2 pieces - the metadata stored in object storage, and snapshots/backups of the persistent volume data. Right now, Velero itself does not encrypt either, instead relying on the native mechanisms in the object and snapshot systems. A special case is restic, which backs up the persistent volume data at the filesystem level and send it to Velero's object storage.

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
Signed-off-by: Madhav Jivrajani <madhav.jiv@gmail.com>

Thank you for contributing to Velero!

# Please add a summary of your change

Added description in the docs under `v1.5/locations.md` and `main/locations.md` under Limitations/Caveats. I've currently followed the description provided in #3065. Please let me know if that's alright.

# Does your change fix a particular issue?

Fixes #3065 

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by jenting — APPROVED** [review]
/lgtm

**Review by nrb — APPROVED** [review]
This is correct, and I think a good location for this information.

**Pull request merged**
