### PR TITLE
Fix the random failure of E2E test cases

### LINKED ISSUE #3970: Get random failure when running the E2E test cases
Sometimes we get the random failure when running the E2E test cases with the following error:
Error in `[Scale]` test case:
```
Errors while attempting to uninstall Velero: "rate: Wait(n=1) would exceed context deadline
```

Error in the following test cases
```
Error creating resource ServiceAccount/velero: serviceaccounts "velero" is forbidden: unable to create new content in namespace velero because it is being terminated
```

The first error may be caused by that the timeout for velero uninstallation is too short, we can try to increase the time. Because of this error,  the uninstallation operation isn't completed, but the following test cases try to install velero again and get the second error

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ywk253100**
Fix the random failure by increasing the timeout and introducing few minor refactor/bug fixes

Fixes #3970

Signed-off-by: Wenkai Yin(尹文开) <yinw@vmware.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by dsu-igeek — DISMISSED** [review]
Looks good, thanks

**Review by jenting — DISMISSED** [review]

**Comment by jenting** [comment]
Please resolve the conflicting files.

**Comment by jenting** [comment]
Please resolve the conflicting files.

**Comment by jenting** [comment]
Please resolve the conflicting files.

**Review by jenting — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]
lgtm

**Review by jenting — APPROVED** [review]

**Pull request merged**
