### PR TITLE
Add labels to expired backups failing garbage collection.

### PR DESCRIPTION
**Pull request by kaovilai**
Thank you for contributing to Velero!

# Please add a summary of your change
If an expired backup garbage collection fails, a label `velero.io/gc-failure=<Reason>` will be added to the backup custom resource.

You can use this label to filter backups that failed to delete.

Implemented reasons are:
- BSLNotFound: Backup storage location not found
- BSLCannotGet: Backup storage location cannot be retrieved from the API server for reasons other than not found
- BSLReadOnly: Backup storage location is read-only

# Does your change fix a particular issue?
Fixes #(issue)
#4728 
# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by sseago** [comment]
@kaovilai A general comment -- several places in this PR reference "labelSelector" when they should just say "label". We're adding labels here. The user would use a label selector with one of these labels to find the resources we label in this PR.

**Review by sseago — DISMISSED** [review]

**Review by sseago — APPROVED** [review]

**Comment by reasonerjt** [comment]
One issue with this approach is that the label may not reflect the most recent failure reason.

Will it have negative impacts?

**Comment by kaovilai** [comment]
> the label may not reflect the most recent failure reason
How so?
Label is a map, and only one value may be assigned to a key `velero.io/gc-failure` at any given time correct?

Are you saying this label should be removed after line 170?  for non-implemented errors failures?
https://github.com/vmware-tanzu/velero/blob/aa3e29384618b1ab4546f3d92fe27c27322d8dc3/pkg/controller/gc_controller.go#L162-L170

**Comment by kaovilai** [comment]
Noted. Will clear if error is not BSL.

**Review by sseago — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Pull request merged**
