### PR TITLE
Added site bio/img for maintainer/contributor sseago

### LINKED ISSUE #3748: Add Scott Seago to the website
Example:

https://github.com/vmware-tanzu/velero/pull/3593

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by sseago**
Signed-off-by: Scott Seago <sseago@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change
Added site bio/img for maintainer/contributor sseago
# Does your change fix a particular issue?

Fixes #3748

# Please indicate you've done the following:

- [ x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by carlisia — CHANGES_REQUESTED** [review]
Hey @sseago, it's not working: https://deploy-preview-3750--velero.netlify.app/ (this is the netlify preview of the website).

I can take a look at the root cause tomorrow if you don't get to it sooner.

This file has instructions for how to run the site locally if you want to do a local test: https://github.com/vmware-tanzu/velero/blob/main/site/README-HUGO.md

**Comment by sseago** [comment]
@carlisia Oops. I had the png filename wrong. It should be fine now.

**Review by carlisia — APPROVED** [review]
Nice!!!

**Review by dsu-igeek — APPROVED** [review]
Looks good, welcome!

**Pull request merged**
