### PR TITLE
v1.4.3 cherry-picks and changelogs

### PR DESCRIPTION
**Pull request by nrb**
I included a change that PV/PVC binding is dependent on, and the CRD restore issue to fix a regression.

### CODE REVIEW

**Comment by nrb** [comment]
Hmmm, I'm not sure what's up with the conflicts. Will investigate.

**Comment by zubron** [comment]
The branch to merge into is marked as "main". Shouldn't it be release-1.4?

**Comment by nrb** [comment]
@zubron Ah, yep. I branched a local `release-1.4` off the wrong upstream. Fixed now!

**Comment by nrb** [comment]
CI isn't getting scheduled - I'm going to close/reopen this.

**Review by zubron — APPROVED** [review]

**Review by carlisia — APPROVED** [review]

**Review by ashish-amarnath — APPROVED** [review]

**Pull request merged**
