### PR TITLE
don't try to back up nonexistent PVCs used by pods

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

xref #1878 

@prydonius @carlisia threw this together to demonstrate https://github.com/vmware-tanzu/velero/issues/1878#issuecomment-545494078 -- WDYT?

### CODE REVIEW

**Comment by prydonius** [comment]
Does the same need to be applied to the PV action? If a PVC is found, but the associated PV isn't?

**Comment by skriss** [comment]
we already have code that only tries to back up a PVC's claimed PV if it's "Bound" -- which isn't exactly the same thing but is probably roughly equivalent. See https://github.com/vmware-tanzu/velero/blob/master/pkg/backup/backup_pv_action.go#L56. I guess we'd have to see if there are any scenarios where the PVC could say it's bound, but the PV doesn't actually exist.

**Comment by prydonius** [comment]
Ah, thanks. Just digged into this and Kubernetes will protect the PV from being deleted if it is bound to a PV (https://v1-12.docs.kubernetes.io/docs/tasks/administer-cluster/storage-object-in-use-protection/#storage-object-in-use-protection-feature-used-for-pv-protection). Forcing a deletion by removing the finalizer causes the PVC to change its status to "Lost". So that check will be sufficient.

**Comment by skriss** [comment]
closing out for now, we'll revisit this topic.

**Pull request closed without merging**
