### PR TITLE
Add nil check before execution of csi snapshot delete

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Signed-off-by: Shubham Pampattiwar <spampatt@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes https://github.com/vmware-tanzu/velero/issues/5400

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by blackpiglet** [comment]
I think after supporting must-include annotation in CSI plugin, the scenario described in #5400 is already fixed.

**Comment by sseago** [comment]
@reasonerjt @blackpiglet I think nil pointer errors are serious enough that we should really check for nil even if we think it's impossible for a particular variable to be nil. They have a way of coming back to haunt us later, and an error which crashes velero is always more serious than an error which results in a backup/restore error.

I think the nil check adds a bit of safety even if we expect it won't happen anymore. Especially considering that it's possible that a user will register an older version of the CSI plugin which doesn't have the annotation.

**Comment by shubham-pampattiwar** [comment]
@reasonerjt @blackpiglet I truly believe that adding a simple check nil check wouldn't hurt. Simply because if the Velero pod restarts then the current backup (which will be in its last stage before completion) will get stuck and Velero would not process it. I think we need this check.

**Comment by blackpiglet** [comment]
I agree that adding more check is helpful.
There is still some check error in this PR. Could you please help to resolve those? I think merging main branch may help to resolve the errors.

**Comment by shubham-pampattiwar** [comment]
@blackpiglet Done, updated the PR.

**Review by blackpiglet — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Pull request merged**
