### PR TITLE
fix: remove pkg/generated

### PR DESCRIPTION
**Pull request by mateusoliveira43**
# Please add a summary of your change

Deleted `pkg/generated/` folder.

# Does your change fix a particular issue?

Fixes https://github.com/vmware-tanzu/velero/issues/6190
Fixes https://github.com/openshift/oadp-operator/issues/1221

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
As @sseago commented with me "regarding removing pkg/generated, that was only deprecated in 1.13, so probably shouldn't remove it until 1.15 at the earliest" I am drafting this PR until it is time, but it should be good enough already, only codecov job failed...

**Comment by blackpiglet** [comment]
The CI job failed with the codecov result uploading.
It's already fixed, please rebase to pick-up it.

**Comment by reasonerjt** [comment]
Per discussion this will be merged post-v1.14

**Comment by blackpiglet** [comment]
We can start to work on this PR because the release-1.14 branch was already cut.

**Comment by mateusoliveira43** [comment]
undrafted the PR

**Review by blackpiglet — APPROVED** [review]

**Comment by blackpiglet** [comment]
https://github.com/dcoapp/app/issues/211#issuecomment-2150514695
The DCO check is blocked by this issue.
Please follow the above comment to push an empty commit to let the check pass.

**Comment by mateusoliveira43** [comment]
done

**Pull request closed without merging**
