### PR TITLE
Clean up unused variables and functions

### PR DESCRIPTION
**Pull request by Fish-pro**
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>

Thank you for contributing to Velero!

# Please add a summary of your change

clean up unused variables and functions

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by Fish-pro** [comment]
@reasonerjt changelog file is required for reporting errors, but I added `/kind Changelog-not-required` as a comment. Could you please give me some guidance?

**Comment by blackpiglet** [comment]
I'm not sure about some parts of PR. Looks like some in-used code is also deleted.

**Comment by Fish-pro** [comment]
> I'm not sure about some parts of PR. Looks like some in-used code is also deleted. And please also run `make update`, then pull again to make the CI go further.

Thanks，I got it

**Comment by Fish-pro** [comment]
@blackpiglet 
I understand that the reason is that when updating this place, I did not pay attention to the order of bag pouring
image

**Review by ywk253100 — APPROVED** [review]

**Review by blackpiglet — APPROVED** [review]

**Pull request merged**
