### PR TITLE
Organize design docs

### PR DESCRIPTION
**Pull request by carlisia**
This should make it easier to identify especially what has already been implemented vs. not.

Signed-off-by: Carlisia <carlisia@vmware.com>

### CODE REVIEW

**Comment by zubron** [comment]
I think I understood merged design docs to be "accepted". At what point will we review the docs under "Submitted" and move them to "Accepted"?

**Review by nrb — DISMISSED** [review]
Merging is acceptance right now, and creating a PR is submitting; I'm not sure I want directories for those. Using directories means there's either right-before-merge or post-merge work to be done to get it into the right directory.

I do think an implemented directory makes sense, though. I think we should write down who moves a design doc into it and when.

**Comment by carlisia** [comment]
I changed to only having an `implemented` directory. I too reached this conclusion after I walked away from it, totally agree!

**Comment by carlisia** [comment]
> I do think an implemented directory makes sense, though. I think we should write down who moves a design doc into it and when.

I think this should be the person implementing the design? But I can't think right now where to write this instruction.

**Review by zubron — APPROVED** [review]
Thanks!

**Comment by zubron** [comment]
> > I do think an implemented directory makes sense, though. I think we should write down who moves a design doc into it and when.
> 
> I think this should be the person implementing the design in the PR for the implementation? But I can't think right now where to write this instruction.

Could this be included in #3102? For example, just including that if a PR is implementing a reviewed design then the associated design doc should also be moved?

**Comment by carlisia** [comment]
> Could this be included in #3102? 

Great idea, done:

https://github.com/vmware-tanzu/velero/pull/3102/files

**Review by nrb — APPROVED** [review]

**Pull request merged**
