### PR TITLE
Bump CRD apiversion to v1

### PR DESCRIPTION
**Pull request by jenting**
After Kubernetes 1.16, the CRD api version change to `apiextensions.k8s.io/v1` and the `apiextensions.k8s.io/v1beta1` is going to be deprecated at Kubernetes 1.19.

This PR bumps the CRS api version via add `crdVersions=v1` flag to `controller-gen` tool, also updates the `controller-gen` tool to the current lastest version `v0.2.4`.

Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>

### CODE REVIEW

**Comment by jenting** [comment]
This PR depends on #2180, and need #2180 to be merged first.

**Comment by carlisia** [comment]
Hey @jenting, #2180 was merged, please rebase this one when you have a chance! Thank you.

**Comment by nrb** [comment]
This is likely to move our required minimum version of Kubernetes upwards; @jenting do you know what version of Kubernetes was the first to introduce v1 of CRDs?

**Comment by jenting** [comment]
Close due to apiVersion v1 supports on K8s 1.16+ only, this PR does not fulfill backward-compatible.

**Comment by jenting** [comment]
Reopen to fix #2159

**Pull request closed without merging**
