### PR TITLE
[doc/resource-filtering.md] typofix

### PR DESCRIPTION
**Pull request by arthurlogilab**

### CODE REVIEW

**Review by nrb — APPROVED** [review]

**Review by ashish-amarnath — APPROVED** [review]

**Comment by ashish-amarnath** [comment]
@arthurlogilab Can you please sign your commits? 
https://github.com/vmware-tanzu/velero/pull/2899/checks?check_run_id=1066287355

**Comment by arthurlogilab** [comment]
@ashish-amarnath this is a typo fix, no I don't have the time to not sign that commit, fee free to change ownership of that commit, sign it your self or delete this pull request.

**Comment by carlisia** [comment]
Hey @arthurlogilab, signing commits is a requirement for every commit. We'll gladly take this over.

I do have to make sure you also know that we have a [Code of Conduct](https://github.com/vmware-tanzu/velero/blob/main/CODE_OF_CONDUCT.md), and the way you are addressing people here is not acceptable.

**Comment by ashish-amarnath** [comment]
The fix had to be made to docs in other versions as well. Closing this in favor of #2917

**Comment by arthurlogilab** [comment]
hi @carlisia @ashish-amarnath thanks for integrating my contribution through that other PR. 

I'm really sorry if my comment came across badly. I'm really glad you have a Code of Conduct and glad to see it can be used when people feel they have been badly treated.  

Another way of phrasing my response, that I hope will be perceived as constructive criticism : I am not (yet) a velero user or contributor, I saw a typo and did a quick edit through the github web interface, I feel like it might be a barrier to contribution to expect 1st time or small documentation contributions to go through the process of gpg signing (which I fully understand for pieces of code). 

Sorry again if I offended anyone.

**Pull request closed without merging**
