### PR TITLE
Remove ReadOnly flag from backupPod Volumes spec

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by weshayutin** [comment]
@shubham-pampattiwar @sseago nice work!

**Review by sseago — APPROVED** [review]

**Comment by sseago** [comment]
@Lyndon-Li this is the change that fixed backup on OpenShift without requiring privileged mode. ReadOnly mount is still preserved since the volumeMount entry still has ReadOnly with this change.

**Comment by Lyndon-Li** [comment]
@sseago @shubham-pampattiwar 
See my comments here https://github.com/vmware-tanzu/velero/pull/8243#issuecomment-2376319885. Let's do some further checks since the readOnly flags in `volumeSource` and `volumeMount` are for different purposes and literally should be both set.

**Comment by sseago** [comment]
Closing in favor of #8250

**Pull request closed without merging**
