### PR TITLE
Blog post announcing Velero 1.5

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

### CODE REVIEW

**Review by zubron — CHANGES_REQUESTED** [review]
This looks good - thanks, @ashish-amarnath! I just have a few comments.

The netlify deploy preview for the blog post doesn't seem to work though. It shows up in the blog post list but when you try to go to the post, it's not found. I'm not sure if that's an issue with the netlify preview or whether there's something else that needs to be fixed here.

Also, looking at the [blog post PR for the 1.4 release](https://github.com/vmware-tanzu/velero/pull/2578/files#diff-626e5bf5a3a45502f781736962886313), the site index file was updated so that the link on the front page points to the latest release blog post. That should be updated here as well.

**Comment by nrb** [comment]
Hmm, the blog post is found when I build the site locally. I wonder if we need to force Netlify to rebuild.

**Comment by ashish-amarnath** [comment]
I pushed the change to update the `site/content/_index.md`  but I still don't see the link work. Locally though, running `make serve-docs`, both links work for me. So not sure what the problem is.

**Comment by nrb** [comment]
@ashish-amarnath Go be on PTO :)

**Comment by zubron** [comment]
It looks like there is an issue with the netlify preview. The link from the index works correctly as it points to https://deploy-preview-2937--velero.netlify.app/blog/velero-1.5-for-and-by-community/
_but_ on the /blog page, the link for the new post is https://deploy-preview-2720--velero.netlify.app/blog/Velero-1.5-For-And-By-Community/
It's using the deploy preview for #2720 for some reason.

**Comment by nrb** [comment]
Even https://5f62492f6652440008e9d7df--velero.netlify.app/ is showing the broken links, and it is definitely using the latest changes.

I'm going to try clearing Netlify's cache and redeploying the preview.

**Comment by nrb** [comment]
Yeah, something's wrong with Netlify, I think.

Even after clearing the cache and rebuilding, using the links on the page go to the 2720 build preview, but if I look at the page directly, the blog post is definitely there: https://5f6262c4f302851fa8d85feb--velero.netlify.app/blog/velero-1.5-for-and-by-community/

@a-mccarthy or @jonasrosland Do you have any suggestions?

**Comment by zubron** [comment]
@nrb this seems like the likely culprit: https://github.com/vmware-tanzu/velero/blob/main/netlify.toml#L12

**Comment by jonasrosland** [comment]
> @nrb this seems like the likely culprit: https://github.com/vmware-tanzu/velero/blob/main/netlify.toml#L12

Yup, definitely, that line shouldn't be in there.

**Comment by nrb** [comment]
Closing in favor of #2940, I don't have access to push to Ashish's remote.

**Pull request closed without merging**
