### PR TITLE
🐛  Patch generated yaml for restore CRD as a hacky workaround

### LINKED ISSUE #2811: 🐛  Velero CRDs from the main branch cannot be installed on a kubernetes 1.18 cluster
See this GH action failures for more info.
https://github.com/vmware-tanzu/velero/actions?query=workflow%3A%22Verify+Velero+CRDs+on+k8s+1.18.4%22

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

Fixes #2811

### CODE REVIEW

**Comment by carlisia** [comment]
I think what's happening is that since "TCP" is the default, it should not be explicitly set, since it is implied. I looked at some other fields that have default values and they were not explicitly set.

**Comment by nrb** [comment]
@carlisia Per https://github.com/kubernetes/kubernetes/issues/91395, though, if it's not set, there's another error.

This seems to be confirming the second case mentioned in 91395.

**Comment by ashish-amarnath** [comment]
I was able to get this to work with a more elegant hack.
@nrb and @carlisia  PTAL

**Comment by carlisia** [comment]
Cool. Would you please mind adding more context as documentation on hack/update-generated-crd-code.sh? Ideally the link to the issue would be used for reference if needed, but we wouldn't have to read the issue to figure out why we have this hack.

What I'd like to see, is there a condition that would allow us to remove this script, what we would have to be on the lookout that would require extending that script if any, anything like that.

**Comment by ashish-amarnath** [comment]
@carlisia added some context to the `update-generated-crd-code.sh` file

**Pull request merged**
