### PR TITLE
Only sync from available BSLs

### PR DESCRIPTION
**Pull request by carlisia**
What do y'all think of this idea?

Mainly:
- if BSL is not available, continue and don't attempt to sync (bc, unavailable)
- only even initialize the backup store if the BSL is available AND the # of items to sync is > 0

Some changes to make this work: a new field `location.Soec.BackupList` would need to be added to the BSL. This field would be a list of strings containing a list of all backups in the store corresponding to that BSL. This field would be populated everytime a BSL was validated.

The sync interval would additionally be dependent on the BSL logic for how frequent to validate a location (https://github.com/vmware-tanzu/velero/blob/main/internal/storage/storagelocation.go#L39-L77).

Signed-off-by: Carlisia <carlisia@vmware.com>

### CODE REVIEW

**Comment by nrb** [comment]
> a new field location.Soec.BackupList would need to be added to the BSL.

1) We may very easily run into Kube API server object size limits with this, because users could have a LOT of backups in a BSL depending on their scheduled frequency.
2)  I think this should be in the `Status` if we're fully managing it, versus letting the user set it.

Would it be possible to record only the number of backups instead of a full list and get the same result? I like the overall idea here, just trying to think of a way to make sure we can scale it.

**Comment by nrb** [comment]
@carlisia What's the status of this PR?

**Comment by carlisia** [comment]
@nrb sorry I missed your question. I will be thinking through this issue and the questions you raised when I start thinking about the CLI work for v1.7, which is soon.

**Comment by dsu-igeek** [comment]
This is superseded by merging the sync and BSL controller together, per Carlisia

**Comment by carlisia** [comment]
I realized I hadn't opened a ticket for this. Here it is: [Merge the BSL and sync controllers · Issue #3908 · vmware-tanzu/velero](https://github.com/vmware-tanzu/velero/issues/3908).

**Pull request closed without merging**
