### PR TITLE
Add time conversion link for community meeting

### PR DESCRIPTION
**Pull request by nrb**
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

### CODE REVIEW

**Comment by jonasrosland** [comment]
I'm happy to move to UTC, but since UTC doesn't observe DST, it would've been 4PM UTC in October and 5PM UTC in November. Do you want to change that during our DST, or are you suggesting we move the meeting to always coincide with 5PM UTC?

**Comment by nrb** [comment]
Ah, good point! I was actually trying to provide a point of reference for folks not in the US, but I didn't think about the DST issue, so I wasn't proposing making changes to ping it to 5pm UTC.

I can do a bit more research here and maybe use GMT, which I think does observe DST.

**Comment by jonasrosland** [comment]
Yes, GMT observes DST, but not at the same dates as the US :)
We could add a link to "Convert to your timezone here" instead, like this?

9AM PT ([click to convert to your time zone](http://www.thetimezoneconverter.com/?t=09:00&tz=PT%20%28Pacific%20Time%29))

**Comment by carlisia** [comment]
OMG TZ!

I love the idea of the TZ converter link, especially since it blocks the 9AM PT box. Let's do that?

**Comment by carlisia** [comment]
I think that's even way better then adding one additional (but specific) reference point.

**Comment by nrb** [comment]
Yeah, I think the converter link is a far better solution too! I'll get that changed.

Thanks Jonas!

**Comment by carlisia** [comment]
image

Source: https://twitter.com/PR0GRAMMERHUM0R/status/1200172543610458112

Thanks for the laugh @nrb!

**Pull request merged**
