### PR TITLE
fix: storage plugin processes leak.

### PR DESCRIPTION
**Pull request by yuanqijing**
Thank you for contributing to Velero!

# Please add a summary of your change
fix https://github.com/vmware-tanzu/velero/issues/7925
# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by sseago** [comment]
@yuanqijing We actually don't need to initialize a new plugin manager at all in FinalizeBackup -- we can pass in the one we already initialized in the backup finalizer controller. I'm testing an alternate fix that does that and will post it if it works.

**Comment by sseago** [comment]
@yuanqijing I've submitted https://github.com/vmware-tanzu/velero/pull/8012 which passes in the already-initialized plugin manager from the finalizer controller, so we don't need to spawn a new plugin process for get/put volume info. I've tested this locally and it resolves the leak.

**Comment by Lyndon-Li** [comment]
#8012 has been merged for #7925, where the backup's `backstore` instance is passed to `FinalizeBackup` and `getVolumeInfos`, so no new plugin manager is initialized.
Therefore, this PR could be closed now.

**Comment by sseago** [comment]
I'm going to go ahead and close this PR since https://github.com/vmware-tanzu/velero/pull/8012 has been merged which also fixes it.

**Pull request closed without merging**
