### PR TITLE
fix `/kind changelog-not-required`

### PR DESCRIPTION
**Pull request by mmorel-35**
Thank you for contributing to Velero!

# Please add a summary of your change

fix `/kind changelog-not-required`

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by blackpiglet — DISMISSED** [review]

**Comment by reasonerjt** [comment]
Please squash the commits.

**Comment by blackpiglet** [comment]
Thanks. I also think that may work after the PR is merged.

I found something useful from the PROW action document.
https://github.com/jpmcb/prow-github-actions/blob/main/docs/labeling.md
The PROW action reads the predefined information from the `.github/labels.yaml`.
@reasonerjt

**Review by blackpiglet — APPROVED** [review]

**Review by sseago — APPROVED** [review]

**Pull request merged**
