### PR TITLE
Update basic-install.md: Add windows cli installation option via chocolatey

### LINKED ISSUE #2081: Add Chocolatey install for Windows CLI
**Describe the problem/challenge you have**
Installing the CLI on Windows is cumbersome, and most other Kubernetes CLI tools we use can be installed via Chocolatey.

**Describe the solution you'd like**
It would be great to have a [Chocolatey](https://chocolatey.org/) install for Windows CLI users.

- OS (e.g. from `/etc/os-release`): Windows 10

### PR DESCRIPTION
**Pull request by adamrushuk**
Closes #2081 as I've just had my Windows Velero CLI package approved on Chocolatey: https://chocolatey.org/packages/velero

Also fixed macos homebrew menu link, as currently not working: https://velero.io/docs/master/basic-install/#option-1-macos---homebrew

### CODE REVIEW

**Comment by adamrushuk** [comment]
> thanks for this @adamrushuk! Everything looks good to me - my only request would be to duplicate the docs change to `site/docs/v1.4/basic-install.md` as well, so it immediately appears in the current release's docs. You'll have to just manually copy the changes in there.

Thanks @skriss good catch.
I've added the same changes to `v1.4` Docs, as requested.

**Comment by adamrushuk** [comment]
Thanks @ashish-amarnath, all great questions, answered below:

* **Are there changes that we need to make to our release tooling to update this package?**
At the moment this is a manual process, but I've already set myself the task to automate new releases.
* **How should we publish newer versions of this package?**
I'm a big fan of Velero, so I'm subscribed to all new releases and am happy to update the Chocolatey package when new versions are released. However, I hope to automate using the recommended Chocolatey methods, once I've tested.
* **How should we handle ownership/maintainership of this package?**
I'm happy to maintain new releases manually until I test and setup automated releases. Once the automated method has been tested and working as expected, I'm happy to maintain or even do another Pull Request if that is preferred.

**Comment by ashish-amarnath** [comment]
@adamrushuk Thank you for clarifying and offering to help us out with the windows packages!
I have one more request before we can have this merged. It would be super useful for the community if you can add the release instructions to our [documentation] (https://github.com/vmware-tanzu/velero/blob/master/site/docs/master/release-instructions.md#post-release---homebrew-version-update)
We would love another PR with the automation.

**Comment by nrb** [comment]
@adamrushuk Thanks for this! I'm very much out of the loop on Windows package managers, but is this compatible with Microsoft's recently announced [WinGet](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/) tool?

**Comment by adamrushuk** [comment]
> @adamrushuk Thank you for clarifying and offering to help us out with the windows packages!
> I have one more request before we can have this merged. It would be super useful for the community if you can add the release instructions to our [documentation](https://github.com/vmware-tanzu/velero/blob/master/site/docs/master/release-instructions.md#post-release---homebrew-version-update)
> We would love another PR with the automation.

I could add the README instructions from my current repo if you'd like? https://github.com/adamrushuk/velero-choco

**Comment by adamrushuk** [comment]
> @adamrushuk Thanks for this! I'm very much out of the loop on Windows package managers, but is this compatible with Microsoft's recently announced [WinGet](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/) tool?

No worries @nrb happy to help if I can!

No, this isn't compatible with WinGet AFAIK, and is very new so I've not had chance to look at WinGet packaging yet. Chocolatey has been around for many years, and is the first public repo most Windows users search in.

**Comment by nrb** [comment]
@adamrushuk Yeah, that's kind of what I figured on both counts :)

**Comment by ashish-amarnath** [comment]
@adamrushuk Just linking your repo in a section of the release doc should do!

**Comment by nrb** [comment]
Merged as I'm ok with release instructions coming in a follow up PR.

**Comment by michmike** [comment]
this is awesome. thank you @adamrushuk

**Comment by adamrushuk** [comment]
> Merged as I'm ok with release instructions coming in a follow up PR.

Thanks @nrb I'll do another PR shortly with link to release instructions.
I'll also keep my eye out for when WinGet becomes GA, then I may add that support too.

> this is awesome. thank you @adamrushuk

Happy to help @michmike :)

**Pull request merged**
