### PR TITLE
Use GitHub Actions to run checks for pushes and pull requests

### PR DESCRIPTION
**Pull request by nrb**
Part of #2104, which will be addressed in parts.

### CODE REVIEW

**Comment by nrb** [comment]
Once this is merged, I can disable PR builds on Travis via their console. This cannot be controlled via the .travis.yml file.

Also, I _believe_ we need to keep Travis building for pushes enabled until we switch our container publishing over, but I'll double check this and update issue #2104 with details.

**Comment by nrb** [comment]
It looks like the workflow didn't trigger from within the PR. The YAML is basically the same as used in the [CSI plug-in](https://github.com/vmware-tanzu/velero-plugin-for-csi/pull/8) repo but with slightly modified names, so you can look there to see what the interface would be.

**Comment by skriss** [comment]
LGTM, let's see what happens on merge :)

**Comment by skriss** [comment]
great success! https://github.com/vmware-tanzu/velero/commit/2cd0b540bd3d5c27eba5cf4c18d371f582c86e93/checks?check_suite_id=365560773

**Pull request merged**
