### PR TITLE
v1.5 blog post

### PR DESCRIPTION
**Pull request by nrb**
Replacement for #2937 since I can't push to Ashish's remote.

### CODE REVIEW

**Comment by jonasrosland** [comment]
Blog looks good, just one minor change I'd like to see, and that's the date in the blog post.

**Comment by carlisia** [comment]
The link to upgrade to 1.5 is broken: https://velero.io/docs/v1.5/upgrade-to-1.5/

**Comment by jonasrosland** [comment]
> The link to upgrade to 1.5 is broken: https://velero.io/docs/v1.5/upgrade-to-1.5/
> 
> This works: https://deploy-preview-2940--velero.netlify.app/docs/v1.5.0-rc.1/upgrade-to-1.5/

1.5 isn't out yet so the docs aren't published for that version yet.

**Comment by carlisia** [comment]
> 1.5 isn't out yet so the docs aren't published for that version yet.

Such a good point 😄

**Comment by nrb** [comment]
Updating the blog post date and the link to github to `v1.5.1` since we'll be doing that tag instead of v1.5.0

**Review by carlisia — APPROVED** [review]
👍

**Review by jonasrosland — APPROVED** [review]

**Comment by nrb** [comment]
Per the [release instructions](https://velero.io/docs/main/release-instructions/), this gets merged _after_ the release.

**Review by a-mccarthy — APPROVED** [review]

**Review by zubron — APPROVED** [review]

**Pull request merged**
