### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by chphong**

### CODE REVIEW

**Review by jenting — CHANGES_REQUESTED** [review]
Thank you, could you please sign the DCO for the commit?

**Review by zubron — CHANGES_REQUESTED** [review]
In addition to signing the commit, you will also need to run `make update` (https://github.com/vmware-tanzu/velero/pull/3352/checks?check_run_id=1768231282#step:3:374) as this change will affect our generated CRDs. Thanks!

**Comment by chphong** [comment]
> Thank you, could you please sign the DCO for the commit?



> In addition to signing the commit, you will also need to run `make update` (https://github.com/vmware-tanzu/velero/pull/3352/checks?check_run_id=1768231282#step:3:374) as this change will affect our generated CRDs. Thanks!

ok

**Comment by chphong** [comment]
how can I add label changelog-not-required to bypass CI ?

**Comment by chphong** [comment]
changelog check failed, should i add a changelog?

**Comment by jenting** [comment]
> changelog check failed, should i add a changelog?

I add change log not required label.

You could bypass the change log check failed since this PR fix typo only. Thank you.

**Review by jenting — APPROVED** [review]
LGTM, thank you.

**Review by zubron — APPROVED** [review]
Thanks! :)

**Pull request merged**
