### PR TITLE
Show yaml example of repository password: file-system-backup.md

### PR DESCRIPTION
**Pull request by kaovilai**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by anshulahuja98 — APPROVED** [review]

**Review by Lyndon-Li — APPROVED** [review]

**Comment by Lyndon-Li** [comment]
@kaovilai Please also cherry-pick this to 1.12 branch. Thanks.

**Comment by allenxu404** [comment]
@kaovilai Could you cherry-pick this PR to release-1.12?

**Comment by kaovilai** [comment]
cherrypick: https://github.com/vmware-tanzu/velero/pull/6787

**Pull request merged**
