### PR TITLE
feat: add ingressclass from ingress

### PR DESCRIPTION
**Pull request by AlbeeSo**
Thank you for contributing to Velero!

# Please add a summary of your change
To backup / restore ingressclass if ingress is backuped and spec.ingressClass is not nil.

After PR, ingressclass will be backuped with logs like
```
time="2024-05-22T17:48:36+08:00" level=info msg="Executing custom action" backup=velero/test-velero-ing logSource="pkg/backup/item_backupper.go:371" name=test-ing namespace=default resource=ingresses.networking.k8s.io
time="2024-05-22T17:48:36+08:00" level=info msg="Executing ingressAction" backup=velero/test-velero-ing cmd=/velero logSource="pkg/backup/actions/ingress_action.go:51" pluginName=velero
time="2024-05-22T17:48:36+08:00" level=info msg="Adding IngressClass nginx to additionalItems" backup=velero/test-velero-ing cmd=/velero logSource="pkg/backup/actions/ingress_action.go:61" pluginName=velero
time="2024-05-22T17:48:36+08:00" level=info msg="Done executing ingressAction" backup=velero/test-velero-ing cmd=/velero logSource="pkg/backup/actions/ingress_action.go:68" pluginName=velero
```
And will be restored with logs like
```
time="2024-05-22T17:59:30+08:00" level=info msg="Executing item action for ingresses.networking.k8s.io" logSource="pkg/restore/restore.go:1319" restore=velero/restore-ing
time="2024-05-22T17:59:30+08:00" level=info msg="Executing AddIngressClassFromIngAction" cmd=/velero logSource="pkg/restore/actions/add_ingressclass_from_ing_action.go:44" pluginName=velero restore=velero/restore-ing
time="2024-05-22T17:59:30+08:00" level=info msg="Adding IngressClass nginx as an additional item to restore" cmd=/velero logSource="pkg/restore/actions/add_ingressclass_from_ing_action.go:54" pluginName=velero restore=velero/restore-ing
```
# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by reasonerjt** [comment]
IMHO, this should remain an "optional" plugin, b/c there may be other cases, where the same ingress will use a different ingressclass, or the same ingressclass like "default" may have different settings across different clusters.
We should be consistent with the way velero handles storageclass, and currently, we don't add storageclass automatically.

**Comment by AlbeeSo** [comment]
> IMHO, this should remain an "optional" plugin, b/c there may be other cases, where the same ingress will use a different ingressclass, or the same ingressclass like "default" may have different settings across different clusters. We should be consistent with the way velero handles storageclass, and currently, we don't add storageclass automatically.

'default' may be different, but if 'default' already exists it will skip to restore by default, right? 
Im curious why storageclass or ingressclass (which is different with volumesnapshotclass) is not automatically added during backup. As usually not-found errors will occur in such cases if they do not exist in restore cluster.  Or the not-found error is expected and users need to adjust it by hand?

**Comment by AlbeeSo** [comment]
> @AlbeeSo As for StorageClass in particular, those are generally configured by the cluster admin. Simply creating a StorageClass kubernetes resource without configuring the storage behind the storageclass wouldn't be helpful. If you are restoring a backup to a cluster where the storageclass for your PVCs doesn't exist, then you'd either need to first get the admin to create and configure that storageclass, or if there's another appropriate storageclass available, then you can use the storageclass mapping feature on restore to use storage already available.



> @AlbeeSo As for StorageClass in particular, those are generally configured by the cluster admin. Simply creating a StorageClass kubernetes resource without configuring the storage behind the storageclass wouldn't be helpful. If you are restoring a backup to a cluster where the storageclass for your PVCs doesn't exist, then you'd either need to first get the admin to create and configure that storageclass, or if there's another appropriate storageclass available, then you can use the storageclass mapping feature on restore to use storage already available.

Got it. So will action like "velero.io/change-ingress-class" be more suitable for this case, or restoring ingress class directly is enough?   @reasonerjt @sseago

**Comment by AlbeeSo** [comment]
IMHO, restoring the ingressclass is enough, and I can add the "velero.io/change-ingress-class" to allow users to change it if need.

**Comment by reasonerjt** [comment]
"velero.io/change-ingress-class" will not be needed as velero now supports resource modifier to modify restored resources in a more general way.

**Comment by reasonerjt** [comment]
Closing this one, given resource modifier will convert this case and a new RIA is not needed.

**Pull request closed without merging**
