### PR TITLE
add null pointer check for vs

### PR DESCRIPTION
**Pull request by cleverhu**
Thank you for contributing to Velero!

# Please add a summary of your change
Add null pointer check for vs.

# Does your change fix a particular issue?

Fixes https://github.com/vmware-tanzu/velero/issues/5438

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by sseago — APPROVED** [review]

**Comment by draghuram** [comment]
Change looks good but while you are modifying the function, the log line at https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_controller.go#L997 seems incorrect.

```logger.Debugf("Deleting VolumeSnapshotContent %s", vsc.Name)```

The following line actually deletes the volume snapshot, not volume snapshot content. Perhaps the message can be fixed in this PR?

**Comment by cleverhu** [comment]
> Change looks good but while you are modifying the function, the log line at https://github.com/vmware-tanzu/velero/blob/main/pkg/controller/backup_controller.go#L997 seems incorrect.
> 
> 
> 
> ```logger.Debugf("Deleting VolumeSnapshotContent %s", vsc.Name)```
> 
> 
> 
> The following line actually deletes the volume snapshot, not volume snapshot content. Perhaps the message can be fixed in this PR?
> 
> 

Ok，I will update the code.

**Review by draghuram — APPROVED** [review]

**Review by sseago — DISMISSED** [review]

**Comment by draghuram** [comment]
@cleverhu Can you please resolve the conflicts?

Can the PR be merged once conflicts are resolved? We are seeing the same crash reported from our users as well (cloudcasa.io).

**Comment by cleverhu** [comment]
> @cleverhu Can you please resolve the conflicts?
> 
> 
> 
> Can the PR be merged once conflicts are resolved? We are seeing the same crash reported from our users as well (cloudcasa.io). 

Ok，I will do it.Thanks

**Comment by blackpiglet** [comment]
https://github.com/vmware-tanzu/velero/pull/5388

**Comment by cleverhu** [comment]
> #5388 This PR already contains the fix.

It seems better, the pr fix a comment for it.

**Comment by blackpiglet** [comment]
Since #5388 is merged, close this one for now. Feel free to reopen to address things not covered.

**Pull request closed without merging**
