### PR TITLE
Propose Scott Seago as a maintainer

### PR DESCRIPTION
**Pull request by nrb**
Scott Seago has made a lot of contributions to Velero, including in
testing, coding, and design.

Some examples of his contributions include a [design for plugin
improvements](https://github.com/vmware-tanzu/velero/blob/main/design/wait-for-additional-items.md),[added skip support to RestoreItemActions](https://github.com/vmware-tanzu/velero/pull/1336), and [reporting important
issues](https://github.com/vmware-tanzu/velero/issues/2948).

He's also been active in the community meetings for the last few years,
and has had thoughtful feedback.

Adding all maintainers since we need quorum for a new maintainer.

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by carlisia** [comment]
That will be a 👍  from me!

@nrb we changed the GH actions recently and the 2 actions that consume the list of maintainers (one that assigns the PR to author, and the one that requests reviews, which is broken at the moment) call this file: `.github/auto-assignees.yml`.

**Review by carlisia — APPROVED** [review]
Welcome @sseago! 🎉  

With this PR approved by everyone, the next step is to add you to the website.

**Review by carlisia — APPROVED** [review]

**Review by jenting — APPROVED** [review]
Welcome~

**Review by dsu-igeek — APPROVED** [review]
Welcome Scott!

**Pull request merged**
