### PR TITLE
Update ROADMAP.md

### PR DESCRIPTION
**Pull request by michmike**

### CODE REVIEW

**Comment by michmike** [comment]
@skriss this is the copy fix you made already :)

**Comment by skriss** [comment]
You mean the progress updates?

**Comment by michmike** [comment]
> You mean the progress updates?

nope, the fix for long running backups that needed to be more reliable wrt creds.
https://github.com/vmware-tanzu/velero/issues/2414

**Comment by skriss** [comment]
ahhh, gotcha

**Pull request merged**
