### PR TITLE
Bump Go to 1.15

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták gliptak@gmail.com

### CODE REVIEW

**Comment by gliptak** [comment]
Anything else here before can be reviewed?

**Comment by gliptak** [comment]
@carlisia @nrb @zubron @ashish-amarnath please review

**Review by zubron — APPROVED** [review]
Thanks!

**Comment by dsu-igeek** [comment]
If we're going to do a 1.15.2 to fix the delete item actions, let's hold this out until after 1.15.2 is cut.  This should get some soak time before releasing.

**Comment by nrb** [comment]
@dsu-igeek Yeah, I wouldn't cherry-pick this back into v1.5.2.

**Comment by nrb** [comment]
@dsu-igeek To be more clear:

I think we could merge this into `main`, and for v1.5.2, we'd only cherry-pick the fixes we want to include. Things like including a Go or Kubernetes version bump wouldn't be included unless it was a major security issues.

**Review by carlisia — APPROVED** [review]
👍

**Pull request merged**
