### PR TITLE
Add Kubernetes v1.22 CI test

### PR DESCRIPTION
**Pull request by jenting**
# Please add a summary of your change

Kubernetes v1.22 released https://github.com/kubernetes/kubernetes/releases/tag/v1.22.0

Add Kubernetes v1.22 CI test for testing CRD verify and E2E test on v1.22.0.

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by zubron — APPROVED** [review]
Thanks, @jenting! I am currently working on a change that will enable the install to pass on 1.22. We were previously ignoring the error when polling for the CRDs but #4002 allows that error to be correctly returned.

**Comment by jenting** [comment]
I am currently working on a change that will enable the install to pass on 1.22.

Thank you @zubron, I'll wait for your PR to fix it :bow:

**Comment by zubron** [comment]
@jenting Can you rebase this onto main? From what I can tell, it looks like the GitHub checkout action creates a merge commit against the original commit you branched from (in this case 8b47596844b73860dd7fbd247a2435028d2deb16) meaning that I can't re-run against the latest commit on main. Thanks!

**Review by zubron — APPROVED** [review]
Woohoo, the tests all passed :tada: Thanks!

**Review by sseago — APPROVED** [review]

**Pull request merged**
