### PR TITLE
Owner reference in backup when created from schedule

### PR DESCRIPTION
**Pull request by matheusjuvelino**
added the option _(useOwnerReferenceInBackup)_  to use the ownerReference when the backup is created by a schedule.

### CODE REVIEW

**Comment by nrb** [comment]
Can you explain more about why one might use this option? What was the motivation for the PR?

**Comment by matheusjuvelino** [comment]
I use argo to manage my applications. When using the velero chart and configuring the schedules, the backups created are "linked" to the main application. For this reason, the application's situation changes to OutOfSync, but if the backup is linked to the schedule, the situation remains Synced.

**Review by nrb — COMMENTED** [review]
Since this doesn't really hurt anything, is technically correct, is off by default, and helps tools like Argo properly keep account of Velero objects I'd be ok with this going in.

Let us know when you take it out of draft!

**Comment by nrb** [comment]
It looks like the CI failure is due to codespell finding a "typo" in the crds.go file, which isn't actually meant to be the literal string. I'm going to see if I can update the codespell job to skip this file, as it's generated and I don't see a way to manually set it to ignore.

**Comment by nrb** [comment]
https://github.com/vmware-tanzu/velero/pull/3174 should take care of it. We may have to close/re-open the PR to trigger the new workflow files once it's merged.

**Review by carlisia — CHANGES_REQUESTED** [review]
Hi @matheusjuvelino, thank you for this. One request: please update the year at the top of this file to be 2020: pkg/apis/velero/v1/schedule.go.

Is this configuration supposed to be done by the user via a CLI flag for the `schedule` cmd, or by editing the manifest?

**Comment by carlisia** [comment]
@nrb CI keeps running the original workflow: https://github.com/vmware-tanzu/velero/actions/runs/411425549/workflow. I don't think there's a way to force it to use [the updated](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/re-running-a-workflow) version.

One way out of this is to disable the workflow all together when this PR is ready to merge, then re-enable right after.

**Comment by matheusjuvelino** [comment]
> Hi @matheusjuvelino, thank you for this. One request: please update the year at the top of this file to be 2020: pkg/apis/velero/v1/schedule.go.
> 
> Is this configuration supposed to be done by the user via a CLI flag for the `schedule` cmd, or by editing the manifest?

@carlisia at the moment is editing the manifest.

**Comment by carlisia** [comment]
I added an issue to add the flag to the `schedule` cmd. This can be done separately: https://github.com/vmware-tanzu/velero/issues/3176. @matheusjuvelino would you like to tackle that one too?

**Review by carlisia — APPROVED** [review]
This lgtm. 👍

**Comment by matheusjuvelino** [comment]
> I added an issue to add the flag to the `schedule` cmd. This can be done separately: #3176. @matheusjuvelino would you like to tackle that one too?

yes I Can

**Review by nrb — APPROVED** [review]

**Comment by igorcezar** [comment]
Will this PR be available only in v1.6?

**Comment by carlisia** [comment]
@igorcezar yes it will be.

**Pull request merged**
