### PR TITLE
wait for informer caches to sync before running controllers

### LINKED ISSUE #616: Use shared informer factory's WaitForCacheSync in server.go
The shared informer factory has a `WaitForCacheSync` method that we can call that will wait for all started informers' caches to sync. For all the places where we have code individually calling `cache.WaitForCacheSync()` with a list of informers **from our standard shared informer factories**, we should be able to remove these calls and rely on a single `factory.WaitForCacheSync()` call instead, in `server.go`.

We also have some informers that are created by hand, separate from the shared informer factories. For these informers, we still need to call `cache.WaitForCacheSync` separately.

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

closes #616  (already closed)

@carlisia @nrb @ashish-amarnath wanted to get your input on this change before making it for all the controllers.  This moves the logic that waits for informers' caches to sync out of each individual controller, and into the main server process, before running any controllers. You can see #616 for a little more detail.

I want to do this because it makes some other refactoring that I'd like to do (basically #131) easier by not requiring each struct that uses an informer/lister to wait for cache sync before using it.

If it looks good to you, I'll continue changing all the other controllers!

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
I am onboard w/ the idea here 👍

**Comment by skriss** [comment]
@ashish-amarnath FYI, I'm hoping that this followed by #131 puts us in a better position to contemplate a potential migration to kubebuilder, since most of the processing logic will have been extracted from our controllers and put into libraries. It also sets us up to more easily move to using worker pods (one per backup/restore) if we decide to go that route.

**Comment by skriss** [comment]
I went ahead and updated all the controllers.

Note we'll hold this until *after* releasing v1.3, so I'm leaving it as a draft.

**Comment by skriss** [comment]
ready for review/merge now that v1.3.0 has been tagged.

**Pull request merged**
