### PR TITLE
Make restore controller adopting the controller-runtime framework.

### LINKED ISSUE #5027: Refactor Restore controller with kubebuilder
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
A sub task of epic #2597 to refactor Restore controller with kubebuilder.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by blackpiglet**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #5027 

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by blackpiglet** [comment]
Basic E2E test result: https://gist.github.com/blackpiglet/fa25ca51ec7e0f1739fa908e59005d64

**Review by qiuming-best — APPROVED** [review]
LGTM

**Comment by sseago** [comment]
@blackpiglet This has conflicts with restore_controller now (I think due to the refactoring to add backup error/warnings, since restore.Result{} was pulled into a shared package). It would be great to get this merged this week, since I may need to deal with minor merge conflicts from some of these files in my current async PR.

**Comment by blackpiglet** [comment]
@sseago 
Resolved the conflict. PTAL.

**Review by sseago — APPROVED** [review]

**Review by shubham-pampattiwar — APPROVED** [review]

**Pull request merged**
