### PR TITLE
Add blog and date to the post urls

### PR DESCRIPTION
**Pull request by jonasrosland**
This will add `/blog/` and date to the blog posts, for better visibility and URL formatting.
I've added redirects/permalinks for all current blog posts, so no existing links should break. There were some images in a blog post that weren't correctly linked, so I fixed those too.

I also changed the redirect file a bit to work better with redirects not focused on the docs.

Signed-off-by: jonasrosland <jrosland@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
Mostly looks good, but when I hit the existing URL for one of the blog posts, e.g. https://deploy-preview-1969--velero.netlify.com/velero-v1-1-on-vsphere/, it redirects to https://deploy-preview-1969--velero.netlify.com/velero-v1-1-on-vsphere/velero.io/blog/2019/10/08/Velero-v1-1-on-vSphere/ and shows a page not found.

**Comment by jonasrosland** [comment]
That's super weird, "Works on my Machine":tm: :)
I'll take a look.

**Comment by jonasrosland** [comment]
There, made a small edit to `config.yaml` so that the redirect function uses the `site.baseurl`, should work fine now.

**Comment by carlisia** [comment]
Why was date added to the URL? I'm not a fan :)

**Comment by jonasrosland** [comment]
> Why was date added to the URL? I'm not a fan :)

Removed the date so it's not simply `/blog/:title`

**Pull request merged**
