### PR TITLE
Updated 1.7 roadmap

### PR DESCRIPTION
**Pull request by eleanor-millman**
Signed-off-by: Eleanor Millman <emillman@vmware.com>

Updated the 1.7 roadmap

# Please indicate you've done the following:

- [X] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [X] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [X] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by eleanor-millman** [comment]
@dsu-igeek Do you want to remove #3531 ?

@reasonerjt Can you please create issues for the three technical health items and link them?

**Comment by eleanor-millman** [comment]
@dsu-igeek Do you want to keep or delete #3531 ?
@reasonerjt Please create and link issues for the first three technical health items.
@phuongatemc I realized I didn't clarify with you the final state of the Plugin Timeouts. Let me know if I should move plugin timeouts from desired to core if you are sure it will be in by the 1.7 release.

Thanks all!

**Comment by ywk253100** [comment]
@eleanor-millman Seems there are some random failures for the e2e case, I'll look into it. And re-run the checking for this PR

**Comment by eleanor-millman** [comment]
Poking @reasonerjt @phuongatemc and @dsu-igeek for the questions I posted above :)

**Comment by phuongatemc** [comment]
> Poking @reasonerjt @phuongatemc and @dsu-igeek for the questions I posted above :)

I recommend to move the plugin timeout out of the 1.7 release for now.  The plugin versioning is heavier than I originally thought so we may not have enough time to cover the timeout.

**Comment by eleanor-millman** [comment]
> > Poking @reasonerjt @phuongatemc and @dsu-igeek for the questions I posted above :)
> 
> I recommend to move the plugin timeout out of the 1.7 release for now. The plugin versioning is heavier than I originally thought so we may not have enough time to cover the timeout.

Sounds good, will do!

**Comment by eleanor-millman** [comment]
Bumping:
@dsu-igeek Do you want to keep or delete #3531 ?
@reasonerjt Please create and link issues for the first three technical health items.

**Comment by eleanor-millman** [comment]
Or, @reasonerjt , I'm ok to have no issues, since it is pretty descriptive what you are doing. Just let me know if you agree.

**Review by dsu-igeek — DISMISSED** [review]
Thanks for updating

**Comment by eleanor-millman** [comment]
@phuongatemc Sorry I dropped the ball on this PR. Before I do my commit, just wanted to confirm that I should still remove the plugin timeout?

And @zubron should I amend it to say that the Plugin versioning will be design doc rather than the feature? Or is it as you said, which is that the design doc really IS the feature?

**Comment by phuongatemc** [comment]
@eleanor-millman  As of this state, I strongly suggest we commit the design doc only.  The implementation would be for next release.  Too much works.

**Comment by eleanor-millman** [comment]
@dsu-igeek @zubron I think I am ready for this to be merged. I pushed an updated commit (plus a merge commit) just now. Are you able to squash and merge? Or do I need to do more things?

**Review by zubron — COMMENTED** [review]
Thanks, @eleanor-millman! Could you follow the steps here to get the DCO check to pass? https://github.com/vmware-tanzu/velero/pull/3934/checks?check_run_id=3305764547
If you need help with it, let me know :)

**Comment by eleanor-millman** [comment]
@zubron Der, I did what you said and it signed the last commit, which was the merge commit. My actual changes commit still doesn't have the signoff. Is there an easy way for me to amend that commit?

**Comment by eleanor-millman** [comment]
https://github.com/vmware-tanzu/velero/pull/4048 is my second try...git got the best of me on this one

**Pull request closed without merging**
