### PR TITLE
bump restic to 0.9.6

### LINKED ISSUE #1253: add support for restic rclone backend
**What steps did you take and what happened:**
I installed velero + restic on Scaleway kubernetes cluster. After having tried some simple backup, I added persistence volume backup on pods in a namespace.

I create the backup:
```
velero backup create gitea --include-namespaces=git
```

No bucket is created, and the backup sticks on "InProgress":
```
velero backup get
NAME      STATUS       CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
gitea     InProgress   0001-01-01 00:00:00 +0000 UTC   29d       default            <none>
```

Note that others backup, without persistence volume backup, are working well. Buckets are created and backups are stored.

**What did you expect to happen:**
Backup of the namespace + volumes in my bucket.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
https://paste.fedoraproject.org/paste/Kq-K~yDb0JAALDLkTTWBSA
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         gitea
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  InProgress

Namespaces:
  Included:  git
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    <n/a>
Completed:  <n/a>

Expiration:  2019-04-03 12:15:09 +0200 CEST

Validation errors:  <none>

Persistent Volumes: <none included>
```
* `velero backup logs <backupname>`
```
velero backup logs gitea
An error occurred: request failed: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><RequestId>tx26c87a0b00024765b7a2f-005c7cfe63</RequestId><Key>backups/gitea/gitea-logs.gz</Key></Error>
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): v0.11.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: kubespray
- Cloud provider or hardware configuration: Scaleway
- OS (e.g. from `/etc/os-release`): Centos 7.4 on server, Fedora 29 for the client

### PR DESCRIPTION
**Pull request by Sh4d1**
Fixes #1253 

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Comment by skriss** [comment]
thanks for the PR @Sh4d1! There's one more place we'll need to update, which is here: https://github.com/vmware-tanzu/velero/blob/master/Makefile#L37, however the v0.9.6 restic binary isn't yet available at that source.

@Prajyot-Parab could you help us get restic v0.9.6 built and published for ppc64 at https://oplab9.parqtec.unicamp.br? Thanks.

**Comment by Prajyot-Parab** [comment]
> thanks for the PR @Sh4d1! There's one more place we'll need to update, which is here: https://github.com/vmware-tanzu/velero/blob/master/Makefile#L37, however the v0.9.6 restic binary isn't yet available at that source.
> 
> @Prajyot-Parab could you help us get restic v0.9.6 built and published for ppc64 at https://oplab9.parqtec.unicamp.br? Thanks.

Yes 
CC - @rpsene

**Comment by rpsene** [comment]
it is here https://oplab9.parqtec.unicamp.br/pub/ppc64el/restic/ 
@Prajyot-Parab @skriss  ^

**Comment by Sh4d1** [comment]
Thanks @rpsene !

@skriss bump the commit to update the Makefile as weel :)

**Pull request merged**
