### PR TITLE
add kindfor func to get apiresource from gvk

### PR DESCRIPTION
**Pull request by runzexia**
Signed-off-by: RyderXia <ryder.xia@sap.com>

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
@runzexia Thank you for your PR!
It would be helpful in reviewing to understand the context of this PR. Is there an issue that you are trying solve with this change?

**Comment by runzexia** [comment]
hi @ashish-amarnath , I develop a plugin to backup helm releases.
in this plugin, i could get GVK from mainifest.
And i need to covert GVK -> metav1.APIResource ->ResourceIdentifier.
If it can be supported in helper, I don't need to maintain many of the same logic in the plug-in code base
https://github.com/runzexia/velero-plugin-helm/blob/master/pkg/plugin/backupplugin.go#L152

**Comment by nrb** [comment]
@runzexia I think that sounds reasonable. Do note https://github.com/vmware-tanzu/velero/issues/2654, where the discovery package is not yet guaranteed to be exposed as part of our public API.

If you're intending to rely on it, please comment on that issue and let us know.

**Comment by nrb** [comment]
I'm ok with including this helper personally, given the explanation.

I'm removing the `On Hold` label as the explanation's been provided and the comment was added to the the API issue.

**Pull request merged**
