### PR TITLE
Remove the [insert current year] in the code standards doc

### PR DESCRIPTION
**Pull request by jenting**
# Please add a summary of your change

Update the code standards documentation, remove the ` [insert current year]`.

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by zubron — APPROVED** [review]
Thanks!

**Comment by dharmab** [comment]
Could you also update the headers? On Linux, this should work:

```
find pkg hack internal -name '*.go' -exec sed -i -E 's/Copyright .+ the Velero contributors\./Copyright the Velero contributors./' {} ';'
```

On macOS, `sed` is BSD instead of GNU and the `-i` flag is different. You could `brew install gsed` and substitute `gsed` there.

**Comment by jenting** [comment]
> Could you also update the headers? On Linux, this should work:
> 
> ```
> find pkg hack internal -name '*.go' -exec sed -i -E 's/Copyright .+ the Velero contributors\./Copyright the Velero contributors./' {} ';'
> ```
> 
> On macOS, `sed` is BSD instead of GNU and the `-i` flag is different. You could `brew install gsed` and substitute `gsed` there.

I'd prefer to create another PR dedicated to this.

**Review by a-mccarthy — APPROVED** [review]
LGTM, thanks @jenting

**Pull request merged**
