### PR TITLE
build(Makefile): add support for building container images for current-context cluster with ttl.sh registry and 24h TTL

### PR DESCRIPTION
**Pull request by kaovilai**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by blackpiglet** [comment]
Could you give more information about the `ttl.sh` registry?

**Comment by kaovilai** [comment]
Follow up enhancements may add a target like so
```Makefile
install-current-context: container-current-context
	go run cmd/velero/velero.go install --image=<image-from-this-pr-target> --provider aws --bucket $AWS_BUCKET --prefix velero --plugins velero/velero-plugin-for-aws:latest --secret-file $AWS_SECRET_FILE
```

**Comment by kaovilai** [comment]
the advantage is user who clone this repo do not need to `docker login someregistry.io` or create a repository to push to.

**Comment by blackpiglet** [comment]
IMO, this change is making developing more convenient, but the `ttl.sh` is not a registry that can host the images for a long time, and I'm not sure whether `ttl.sh` is available for most environments, for example, I'm blocked from it by the firewall.

As a result, I suggest to keep this change as private.

**Comment by kaovilai** [comment]
ack. you can always use your own registry and override with if that's preferable. or this can be modified to require your own registry. If that's desirable lmk. Closing for now.

**Pull request closed without merging**
