### PR TITLE
add a storage supported provider : HuaweiCloud OBS

### PR DESCRIPTION
**Pull request by setoru**
# Please add a summary of your change

Update docs to add HuaweiCloud OBS for HuaweiCloud Provider.

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file (`make new-changelog`)](https://velero.io/docs/main/code-standards/#adding-a-changelog) or comment `/kind changelog-not-required` on this PR.
- [x] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by kaovilai — COMMENTED** [review]
Are you working on this on a personal capacity? The repo referenced is on a personal account rather than as part of an organization.

**Comment by setoru** [comment]
> Are you working on this on a personal capacity? The repo referenced is on a personal account rather than as part of an organization.

Yes, I am working on this in a personal capacity, and the referenced repo is indeed under my personal account.

**Review by kaovilai — APPROVED** [review]

**Comment by kaovilai** [comment]
fixing changelog check

**Review by reasonerjt — APPROVED** [review]
lgtm

**Pull request merged**
