### PR TITLE
[GH-1505] add documentation regarding autocompletion for velero CLI

### PR DESCRIPTION
**Pull request by cpanato**
- Add documentation in how to setup autocompletion for Velero CLI

  fixes: https://github.com/vmware-tanzu/velero/issues/1505 

Instructions tested on:
- [x] Linux Ubuntu 18.04 - bash
- [x] Linux Ubuntu 18.04 - zsh
- [x] macOS Catalina - bash
- [x] macOS Catalina - zsh

### CODE REVIEW

**Comment by skriss** [comment]
Thanks for this @cpanato, this is great! I tried out the macOS instructions and they worked liked a charm :+1:

The only thought I have is that we might want to locate this on a different page, to avoid making the "basic install" page too cluttered. One option would be to create a new page with this info, and add a link to it right at the bottom of the "Install the CLI" section. What does everyone think?

**Comment by ashish-amarnath** [comment]
I agree with @skriss We might want to relocate this on the Customize-Installation page.

**Comment by cpanato** [comment]
@skriss @ashish-amarnath done, please let me know your thoughts

**Comment by cpanato** [comment]
@ashish-amarnath should I open another PR when this gets merge to cherry-pick this changes to the v1.2.0?

**Comment by skriss** [comment]
LGTM. @cpanato to replicate this addition for the `v1.2.0` docs, you'll need to manually apply the same changes to the docs under `site/docs/v1.2.0`. We usually do this in the same PR as the `site/docs/master` changes. Once you do that, I think we're good to merge here!

**Comment by cpanato** [comment]
@skriss done added the docs to 1.2.0

**Pull request merged**
