### PR TITLE
add support for getting Azure Storage Account key from ENV variable

### LINKED ISSUE #2376: Restic - add support setting Azure Storage Account Key via configuration
**Describe the problem/challenge you have**

There is a PR pending in Velero's Azure plugin https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/32. The same support for setting Storage Account Key via configuration should be added into `pkg/restic/azure.go`

**Describe the solution you'd like**

Implement the same approach as in https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/32.

**Environment:**

- Velero version (use `velero version`): 1.13.1
- Kubernetes version (use `kubectl version`): 1.16.7
- Kubernetes installer & version: PaaS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

### PR DESCRIPTION
**Pull request by jaygridley**
This PR closes #2376.

### CODE REVIEW

**Comment by skriss** [comment]
@jaygridley this looks good to me - can you just add a changelog file (`changelogs/unreleased/2455-jaygridley`) with a brief description of the change?

**Comment by skriss** [comment]
@jaygridley gentle reminder that we're just waiting on a changelog file from you here. Thanks!

**Comment by carlisia** [comment]
👆

**Comment by skriss** [comment]
I'd say let's merge this and I'll add a changelog file in a separate PR.

**Comment by skriss** [comment]
changelog PR added: https://github.com/vmware-tanzu/velero/pull/2491

let's get these merged!

**Comment by skriss** [comment]
also note I added #2476 to the backlog

**Comment by jaygridley** [comment]
Sorry guys. I was out with proper access. Is there any work needed?

**Comment by skriss** [comment]
nope, we took care of it. thanks for the PR!

**Pull request merged**
