### PR TITLE
Increase ensure restic repository timeout

### PR DESCRIPTION
**Pull request by shubham-pampattiwar**
Signed-off-by: Shubham Pampattiwar <spampatt@redhat.com>

Fixes https://github.com/vmware-tanzu/velero/issues/5334

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by reasonerjt** [comment]
I'd suggest we spend a little more time to find the root cause like is it due to the locking mechanism causing things to be sequential when they don't have to.

If we don't have a better solution till FC we'll merge this PR.

**Comment by weshayutin** [comment]
Looks good, thank you @shubham-pampattiwar

**Review by eemcmullan — APPROVED** [review]

**Review by kaovilai — APPROVED** [review]
LGTM!

**Comment by kaovilai** [comment]
For 1.10+ (and `main`) I would consider making the timeout configurable if we couldn't find root cause before merging this PR.

**Review by reasonerjt — APPROVED** [review]

**Review by qiuming-best — APPROVED** [review]

**Pull request merged**
