### PR TITLE
release instructions

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

FYI @nrb @prydonius @carlisia 

I wrote these based on notes/memory/today's release, so hopefully they're pretty complete & accurate, but I'll do some review and testing of parts to ensure they're valid before merge.

There's also definitely room for improvement here, I'd like to automate away a lot of this now that we're in a fairly stable place, so definitely review this with an eye towards how we can do that.

### CODE REVIEW

**Comment by prydonius** [comment]
This is really great, thanks for writing this up @skriss!

**Comment by skriss** [comment]
Made a couple edits.

Ready for review/merge.  We'll follow these instructions for the next release to validate them and make any edits necessary.

**Comment by carlisia** [comment]
Yes, this looks great. I think we'd have to use it to find opportunities for improvements, just reading it looks complete. Except, is it worthwhile adding a list of the places where we need to announce releases (twitter, google group, slack)? Does this belong here?

**Comment by skriss** [comment]
Yep, sure, will add.

**Pull request merged**
