### PR TITLE
changelog for 2944

### PR DESCRIPTION
**Pull request by mickkael**

### CODE REVIEW

**Comment by ashish-amarnath** [comment]
PR https://github.com/vmware-tanzu/velero/pull/2944 has not been merged yet, so the changelog can be added as part of https://github.com/vmware-tanzu/velero/pull/2944.

@mickkael can you please add the changelog to be part of the PR https://github.com/vmware-tanzu/velero/pull/2944?
Closing this PR

**Comment by ashish-amarnath** [comment]
based on @nrb''s comment, reopening for discussion https://github.com/vmware-tanzu/velero/pull/2944#issuecomment-698557549

**Comment by nrb** [comment]
@ashish-amarnath I think 2944 was made via the GitHub web interface, and I'm not looking to put a barrier up for someone's contribution if we have the changelog in some way, shape, or form.

**Comment by ashish-amarnath** [comment]
@nrb thanks for that context. Are we also not enforcing the DCO check then?

**Comment by nrb** [comment]
@ashish-amarnath That's a good point. The DCO still needs to be signed as a legal requirement for contribution.

**Comment by ashish-amarnath** [comment]
@mickkael Can you please signoff your commits? https://github.com/vmware-tanzu/velero/pull/2955/checks?check_run_id=1136970285

**Pull request closed without merging**
