### PR TITLE
Fix condition matching in resource modifier when there are multiple rules

### LINKED ISSUE #7714: Resource Modifier: Condition matching is incorrect when there are multiple rules
**What steps did you take and what happened:**
1. define a resource modifier to update storageClass name in pvc in this rule: a=>b, b=>c
2. run velero restore
3. result: a=>c, b=>c

```
version: v1
resourceModifierRules:
- conditions:
    groupResource: persistentvolumeclaims
  matches:
    - path: "/spec/storageClassName"
      value: "a"
  patches:
  - operation: replace
    path: "/spec/storageClassName"
    value: "b"
- conditions:
    groupResource: persistentvolumeclaims
  matches:
    - path: "/spec/storageClassName"
      value: "b"
  patches:
  - operation: replace
    path: "/spec/storageClassName"
    value: "c"
```

**What did you expect to happen:**
a=>b, b=>c

**Anything else you would like to add:**
The same problem will occur in other situations if any field that affects the condition matching is changed in patch.

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by 27149chen**
# Please add a summary of your change

Fix condition matching in resource modifier when there are multiple rules

# Does your change fix a particular issue?

Fixes #7714

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by reasonerjt** [comment]
@27149chen Could you rebase to fix the linter errors?

**Comment by anshulahuja98** [comment]
PR LGTM - @27149chen can you please consider adding a unit test for the scenario you described in the issue to ensure we do not regress this in future and the behaviour is captured in the UTs atleast.

**Comment by anshulahuja98** [comment]
gentle ping @27149chen

**Comment by 27149chen** [comment]
> gentle ping @27149chen

ut added, apologies for the delay

**Comment by 27149chen** [comment]
> @27149chen Could you rebase to fix the linter errors?

done

**Comment by blackpiglet** [comment]
@27149chen 
Sorry for interruption again, the CI action failed due to go.mod file is out-of-date.

**Comment by 27149chen** [comment]
> @27149chen Sorry for interruption again, the CI action failed due to go.mod file is out-of-date.

@blackpiglet , I have run go mod tidy, but with no help

**Comment by blackpiglet** [comment]
@27149chen 
I rebase and squash the commits. The go module issue is fixed.
Hope that's OK for you.

Please check out and sign off again to make the DCO check pass.

**Review by anshulahuja98 — APPROVED** [review]

**Comment by 27149chen** [comment]
> @27149chen I rebase and squash the commits. The go module issue is fixed. Hope that's OK for you.
> 
> Please check out and sign off again to make the DCO check pass.

@blackpiglet thanks, DCO looks right

**Review by sseago — APPROVED** [review]

**Pull request merged**
