### PR TITLE
[cherry-pick]Support both v1beta1 and v1 CRDs for velero

### PR DESCRIPTION
**Pull request by ywk253100**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required`.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by jenting — APPROVED** [review]

**Review by zubron — APPROVED** [review]
Thanks!

**Comment by zubron** [comment]
@ywk253100 Can you run `make update` and push the changes? The CRDs are slightly different on this branch as a new field was added to the Backup and Schedule CRDs post 1.6 which is not in this branch. See #3641.

**Comment by ywk253100** [comment]
@zubron @jenting I have updated the PR, please take a look again, thanks

**Review by jenting — APPROVED** [review]

**Review by zubron — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
