### PR TITLE
Make pkg/install/Deployment podTemplateOptions bool functions accept bool param

### LINKED ISSUE #7379: Make pkg/install/Deployment podTemplateOptions bool functions accept bool param
**Describe the problem/challenge you have**

Since [podTemplateOptions](https://github.com/vmware-tanzu/velero/blob/main/pkg/install/deployment.go#L32C46-L32C48) is not exported, it is not possible to form an array of podTemplateOptions to pass to install.Deployment().

Anyone using this package would require each exported function that returns an unexported type to be used directly in install.Deployment().

Thus it would be good to make these functions flexible for use by other go packages.

**Describe the solution you'd like**

Either make all bool related funcs accept bool param, or export the type so an array can be formed dynamically.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by kaovilai**
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #7379

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by blackpiglet** [comment]
IMO, this doesn't make a difference between the original functions.
We can choose not to call the `WithRestoreOnly` function to set the `--restore-only` as `false`.

**Comment by kaovilai** [comment]
@blackpiglet the alternative would be to make `podTemplateConfig` into `PodTemplateConfig` so that i can form dynamically an array of `[]PodTemplateConfig` functions outside of this package.

**Comment by kaovilai** [comment]
for context this is for external consumption of these functions

See: https://github.com/vmware-tanzu/velero/issues/7379#issuecomment-1928737844

WIthout this Bool func that accepts a param, or alternatively exporting the type, I cannot store these podTemplateOption functions in a slice to pass to `install.Deployment(slice...)` outside of the install package.

**Comment by blackpiglet** [comment]
> for context this is for external consumption of these functions
> 
> See: [#7379 (comment)](https://github.com/vmware-tanzu/velero/issues/7379#issuecomment-1928737844)
> 
> WIthout this Bool func that accepts a param, or alternatively exporting the type, I cannot store these podTemplateOption functions in a slice to pass to `install.Deployment(slice...)` outside of the install package.

I see. I suggest refactoring those existing functions to suit your scenario instead of keeping the old and the new ones together.

**Review by blackpiglet — APPROVED** [review]

**Review by reasonerjt — APPROVED** [review]

**Pull request merged**
