### PR TITLE
Add oc patch commands for DS

### PR DESCRIPTION
**Pull request by git001**
From my point of view is it much easier to run oc commands instead of editing a yaml file.
My proposel is to offer the user both methodes, manuall edit and automatic edit.

This is second try for PR #2103

Signed-off-by: git001 alex <al-git001@none.at>

### CODE REVIEW

**Comment by carlisia** [comment]
Hi @git001 while we get this reviewed, please make sure to get the CDO passing, thank you.

**Comment by git001** [comment]
Hi @carlisia I use the git web interface. It looks like that this interface can't sign the pull request.
I just wanted to contribute, it's repo team to decide to accept this PR or not, both is okay for me.

**Comment by carlisia** [comment]
Hey @git001, I found a couple ways you can sign the PR using the web UI!

1) use a browser extension: https://chrome.google.com/webstore/detail/dco-github-ui/onhgmjhnaeipfgacbglaphlmllkpoijo

2) manually add a line to your commit message, like:

```
Signed-off-by: shashank855 <shashank.ranjan@mayadata.io>
```

(fill in your name and email)

**Comment by git001** [comment]
Thanks for your hints.  
Tried the 2nd option because I don't like this chrome stuff, maybe I have used it wrong. However it tooks me too much time for such a small contribution.  
Looks like it's quite complicated to pass this DCO from web gui, again accept it or leave it, both are fine for me.

**Comment by skriss** [comment]
@git001 thanks for the contribution here! I opened #2136 using your content to get around the DCO issue, and added you as a co-author for credit. I'll close this PR out.

**Pull request closed without merging**
