### PR TITLE
Fix tiltfile: go install command instead of go get

### LINKED ISSUE #5950: tilt up failed cause the go get is not supported anymore.
**What steps did you take and what happened:**

image

**What did you expect to happen:**
tilt up successfully

**The following information will help us better understand what's going on**:

**Anything else you would like to add:**

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by abserari**
Thank you for contributing to Velero!

# Please add a summary of your change
make changes: go install command instead of go get

question:
- [ ] I don't test the dlv version and use the latest, don't know the update if would work in the following work.

Now tilt up success. Finally.
image

# Does your change fix a particular issue?

Fixes #5950

# Please indicate you've done the following:

- [x] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [x] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by anshulahuja98** [comment]
LGTM

**Comment by kaovilai** [comment]
Are the current docs for getting tilt working still accurate with this PR?

**Comment by abserari** [comment]
> Are the current docs for getting tilt working still accurate with this PR?

The tilt doc doesn't mention the go install script, because it is included by tilt steps. `tilt up` is all we read about the doc.

**Review by kaovilai — APPROVED** [review]

**Comment by anshulahuja98** [comment]
https://github.com/vmware-tanzu/velero/pull/6223/files
This change got checked in in above PR, I think we can close this PR.

**Comment by abserari** [comment]
I'm a little confused.

fine

**Pull request closed without merging**
