### PR TITLE
Fix:rss link blindly appends /blog/index.html

### LINKED ISSUE #3882: rss link blindly appends /blog/index.html
**What steps did you take and what happened:**
1. visit https://velero.io/
2. clicked `see all posts` to see the blog, browser went to https://velero.io/blog/
3. clicked RSS icon to check for xml
4. was navigated to https://velero.io/blog/blog/index.xml (404)

**What did you expect to happen:**
Go directly to https://velero.io/blog/index.xml

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #3882

### CODE REVIEW

**Comment by zubron** [comment]
Hi @Patil2099 - thanks for fixing this! All commits must be signed in order for us to merge. Please follow the instructions here: https://github.com/vmware-tanzu/velero/pull/3886/checks?check_run_id=2859711068

**Comment by Patil2099** [comment]
@zubron I think it is ready now.

**Review by zubron — APPROVED** [review]
Thanks!

**Review by jenting — APPROVED** [review]
Thank you @Patil2099

**Pull request merged**
