### PR TITLE
Fix node-agent missing metrics-addr parms to define the server start. #6784

### PR DESCRIPTION
**Pull request by yanggangtony**
Thank you for contributing to Velero!

# Please add a summary of your change
Fix node-agent missing metrics-addr parms to define the server start.

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Review by kaovilai — APPROVED** [review]

**Comment by allenxu404** [comment]
Taking a quick look at this PR, I think the daemonset of node agent should also expose the container port same as how Velero deployment works:
https://github.com/vmware-tanzu/velero/blob/8a366c6924a756e70cd352a6063aaaf38ec30e9f/pkg/install/deployment.go#L217C42-L217C42

**Comment by yanggangtony** [comment]
@allenxu404 
>>>```Taking a quick look at this PR, I think the daemonset of node agent should also expose the container port same as how Velero deployment works:```

Good catch . 
Would you suggest arise another pr for fix that?
Or just in this one?

**Comment by yanggangtony** [comment]
I pushd again.
Because this is related to the metrics port..

**Review by allenxu404 — APPROVED** [review]

**Comment by allenxu404** [comment]
@yanggangtony Can you help repush the PR to trigger CI again since the checks didn't pass on the last run?

**Comment by yanggangtony** [comment]
Yep , rebased.

**Comment by yanggangtony** [comment]
Now the codecov shows code diff issues.
I see too many this errors in others prs.😀😀

**Review by ywk253100 — APPROVED** [review]

**Review by blackpiglet — APPROVED** [review]

**Pull request merged**
